#!/bin/bash
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2019 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

export WAF_SUFFIX=`basename $0 | sed 's/^waf_//'`
if [ ${WAF_SUFFIX} = "waf" ]; then
    WAF_SUFFIX=$(readlink $0 | sed 's/^waf_//')
fi

export WAFLOCK=.lock-${WAF_SUFFIX}_build

# default arguments value
builddir="build/${WAF_SUFFIX}"
jobs=4

# backup original arguments
orig="$@"
OPTS=$(getopt --quiet -o o:j: --long out:,jobs: -n $(basename $0) -- "$@")
eval set -- "$OPTS"
while true; do
    case "$1" in
        -o | --out ) builddir="$2"; shift ;;
        -j | --jobs ) jobs="$2"; shift ;;
        -- ) shift; break ;;
        * ) break ;;
    esac
    shift
done

./waf.main ${orig} --out=${builddir} --jobs=${jobs}
