!
! COPYRIGHT (C) 1991 - 2017  EDF R&D                WWW.CODE-ASTER.ORG
!
! THIS PROGRAM IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR MODIFY
! IT UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY
! THE FREE SOFTWARE FOUNDATION; EITHER VERSION 2 OF THE LICENSE, OR
! (AT YOUR OPTION) ANY LATER VERSION.
!
! THIS PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT
! WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
! MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. SEE THE GNU
! GENERAL PUBLIC LICENSE FOR MORE DETAILS.
!
! YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE
! ALONG WITH THIS PROGRAM; IF NOT, WRITE TO EDF R&D CODE_ASTER,
! 1 AVENUE DU GENERAL DE GAULLE, 92141 CLAMART CEDEX, FRANCE.
!
! -------------------------------------------------------------------------
! asteryacs constants
! -------------------------------------------------------------------------
!





! almost a type



#define yadr '&&YACS'
#define slots '&&YACS.SLOTS'




#define PORT_NAME_PARAMI 'PARAMI'
#define PORT_NAME_PARAMR 'PARAMR'


#define PORT_DEPL 1
#define PORT_NAME_DEPL 'DEPL'
#define PORT_NAME_INFO_DEPL 'INFO_DEPL'
#define ASTER_BUFF_DEPL '&&YACS.BUFF_DEPL'

#define PORT_VIT  2
#define PORT_NAME_VIT 'VIT'
#define PORT_NAME_INFO_VIT 'INFO_VIT'
#define ASTER_BUFF_VIT '&&YACS.BUFF_DEPL'

#define PORT_FORCE  3
#define PORT_NAME_FORCE 'FORCE'
#define PORT_NAME_INFO_FORCE 'INFO_FORCE'
#define ASTER_BUFF_FORCE '&&YACS.BUFF_FORCE'


