#!/usr/bin/env python3
# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2020 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

"""
    %(prog)s [options]

"""

import argparse
import os
import os.path as osp
import sys


try:
    from run_aster import RunAster
except ImportError:
    root = osp.dirname(osp.dirname(osp.abspath(__file__)))
    lib = osp.join(root, "lib", "aster")
    sys.path.append(lib)
    from run_aster import RunAster

from run_aster.logger import DEBUG, logger


__DOC__ = __doc__


def parse_args(argv):
    """Parse command line arguments.

    Arguments:
        argv (list): List of command line arguments.
    """
    # command arguments parser
    parser = argparse.ArgumentParser(
        usage=__DOC__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-g', '--debug', action='store_true')
    parser.add_argument('export', metavar='EXPORT',
                        help="Export file defining the calculation.")

    args = parser.parse_args(argv)
    if args.debug:
        logger.setLevel(DEBUG)
    return args


def main(argv=None):
    """Entry point for code_aster runner.

    Arguments:
        argv (list): List of command line arguments.
    """
    args = parse_args(argv or sys.argv[1:])
    calc = RunAster(args.export)
    calc.run()


if __name__ == '__main__':
    main()
