#!/usr/bin/env python3
# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2020 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

# This only to show debug informations as soon as possible
# aslint: disable=C4008

"""
    %(prog)s [options]

"""

import argparse
import os
import os.path as osp
import sys

try:
    import ptvsd
    HAS_PTVSD = True
except ImportError:
    HAS_PTVSD = False


try:
    import run_aster
except ImportError:
    root = osp.dirname(osp.dirname(osp.abspath(__file__)))
    lib = osp.join(root, "lib", "aster")
    sys.path.append(lib)

from run_aster.logger import DEBUG, logger


__DOC__ = __doc__


def parse_args(argv):
    """Parse command line arguments.

    Arguments:
        argv (list): List of command line arguments.
    """
    # command arguments parser
    parser = argparse.ArgumentParser(
        usage=__DOC__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-g', '--debug', action='store_true',
                        help="print debugging information (same as "
                             "DEBUG=1 in environment)")
    parser.add_argument('--ptvsd', action='store', type=int,
                        help="ptvsd port number")
    parser.add_argument('-w', '--wrkdir', action='store',
                        help="use this existing directory as working directory")
    parser.add_argument('export', metavar='EXPORT',
                        help="Export file defining the calculation.")

    args = parser.parse_args(argv)
    if args.debug:
        logger.setLevel(DEBUG)
    return args


def main(argv=None):
    """Entry point for code_aster runner.

    Arguments:
        argv (list): List of command line arguments.
    """
    args = parse_args(argv or sys.argv[1:])
    from run_aster.run import RunAster, temporary_dir

    if args.ptvsd:
        print('Waiting for debugger attach...'),
        ptvsd.enable_attach(address=('127.0.0.1', args.ptvsd))
        ptvsd.wait_for_attach()
        ptvsd.break_into_debugger()

    calc = RunAster(args.export)
    if args.wrkdir:
        os.chdir(args.wrkdir)
        calc.execute()
    else:
        with temporary_dir():
            calc.execute()


if __name__ == '__main__':
    main()
