# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2020 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------
  
import code_aster
from code_aster.Commands import *
import numpy as np

DEBUT(CODE=_F(NIV_PUB_WEB='INTERNET'),DEBUG=_F(SDVERI='OUI'))

# maillage, modele, caraelem

maillage = code_aster.Mesh()
maillage.readMedFile("sdll154a.mmed")

modele = AFFE_MODELE(MAILLAGE = maillage,
                    AFFE = _F(MODELISATION = "POU_D_T",
                              PHENOMENE = "MECANIQUE",
                              TOUT = "OUI",))

acier=DEFI_MATERIAU(ELAS=_F(E = 2.E11,
                            RHO = 7800,
                            ALPHA = 1.2E-5,
                            NU = 0.3),
                    RAMBERG_OSGOOD=_F(FACTEUR=0.01,
                                     EXPOSANT=2)
                    )


t_ini=CREA_CHAMP(
    TYPE_CHAM='NOEU_TEMP_R', OPERATION='AFFE', MODELE=modele,
    AFFE=_F(TOUT='OUI', NOM_CMP='TEMP', VALE=20,),)

t_final=CREA_CHAMP(
                            TYPE_CHAM='NOEU_TEMP_R', OPERATION='AFFE', MODELE=modele,
                            AFFE=_F(TOUT='OUI', NOM_CMP='TEMP', VALE=120.0,),)

resu_temp = CREA_RESU(TYPE_RESU = 'EVOL_THER',
                        NOM_CHAM='TEMP',
                        OPERATION='AFFE',
                        AFFE=(
                            _F(CHAM_GD=t_ini, INST=0.0),
                            _F(CHAM_GD=t_final, INST=1.0),))


ch_mater=AFFE_MATERIAU(MAILLAGE=maillage,
                       AFFE_VARC=_F(TOUT='OUI',NOM_VARC = 'TEMP',EVOL=resu_temp,VALE_REF=20.0,),
                       AFFE=_F(TOUT="OUI", MATER = acier))

cara_elem=AFFE_CARA_ELEM(MODELE=modele, INFO=2,
                         POUTRE=_F(GROUP_MA="TUYAU", SECTION = 'CERCLE',
                                   CARA = ('R', 'EP'),
                                   VALE = (0.01, 0.005)))

# conditions aux limites

blocage_a = AFFE_CHAR_MECA(MODELE=modele,
                           DDL_IMPO=(_F(GROUP_NO='A',
                                        DX=0,DY=0,DZ=0,DRX=0, DRY=0, DRZ=0)))

blocage_b = AFFE_CHAR_MECA(MODELE=modele,
                           DDL_IMPO=(_F(GROUP_NO='B',
                                        DX=0, DZ=0)))

deplacement_b = AFFE_CHAR_MECA(MODELE=modele,
                               DDL_IMPO=(_F(GROUP_NO='B',
                                               DRX=0.02,)))

poids = AFFE_CHAR_MECA(MODELE=modele,
                       PESANTEUR=_F(GRAVITE=9.81,DIRECTION=( 0., 0., -1.),)
                       )

acce_xy=DEFI_FONCTION(NOM_PARA='FREQ',    INTERPOL='LOG',
                      VALE=(1.0, 1.962, 10.0, 19.62,
                            30.0,  19.62,   100.0,    1.962,
                            10000.0,   1.962,          )       )
spect_xy=DEFI_NAPPE(NOM_PARA='AMOR',
                    INTERPOL=('LIN', 'LOG'),
                    PARA=(0.015, 0.02, 0.025,),
                    FONCTION=(acce_xy, acce_xy, acce_xy))

# modes

ASSEMBLAGE(MODELE=modele,
           CHAM_MATER=ch_mater,
           CARA_ELEM=cara_elem,
           CHARGE=(blocage_a, blocage_b),
           NUME_DDL=CO('nddl'),
           MATR_ASSE=(_F(MATRICE=CO('matrice_rigi'),
                         OPTION='RIGI_MECA',),
                      _F(MATRICE=CO('matrice_mass'),
                         OPTION='MASS_MECA',),),);

modes_dyn=CALC_MODES(MATR_RIGI=matrice_rigi,
                     MATR_MASS=matrice_mass,
                     CALC_FREQ=_F(NMAX_FREQ=4),
                     )
modes_dyn=CALC_CHAMP(reuse=modes_dyn,
                     RESULTAT=modes_dyn,
                     CONTRAINTE='EFGE_ELNO')

modes_sta=MODE_STATIQUE(MATR_RIGI=matrice_rigi,
                        MATR_MASS=matrice_mass,
                        PSEUDO_MODE=_F(  AXE = ( 'X',  'Y',  'Z', )))
modes_sta=CALC_CHAMP(reuse=modes_sta,
                     RESULTAT=modes_sta,
                     CONTRAINTE='EFGE_ELNO')

# resultats

poids_propre = MECA_STATIQUE(MODELE=modele,
                             CHAM_MATER=ch_mater,
                             CARA_ELEM=cara_elem,
                             EXCIT=(_F(CHARGE=blocage_a),
                                    _F(CHARGE=poids)),
                             INST = 0.0)
poids_propre = CALC_CHAMP(reuse=poids_propre,
                            RESULTAT=poids_propre,
                            CONTRAINTE='EFGE_ELNO')

deplacement_impose = MECA_STATIQUE(MODELE=modele,
                                   CHAM_MATER=ch_mater,
                                   CARA_ELEM=cara_elem,
                                   EXCIT=(_F(CHARGE=blocage_a),
                                           _F(CHARGE=deplacement_b)),
                                   INST = 0.0)
deplacement_impose = CALC_CHAMP(reuse=deplacement_impose,
                                RESULTAT=deplacement_impose,
                                CONTRAINTE='EFGE_ELNO')

dilatation_thermique = MECA_STATIQUE(MODELE=modele,
                                     CHAM_MATER=ch_mater,
                                     CARA_ELEM=cara_elem,
                                     EXCIT=(_F(CHARGE=blocage_a,),
                                            _F(CHARGE=blocage_b,)),
                                     INST = 1.0)
dilatation_thermique = CALC_CHAMP(reuse=dilatation_thermique,
                                  RESULTAT=dilatation_thermique,
                                  CONTRAINTE='EFGE_ELNO')

sismique = COMB_SISM_MODAL(MODE_MECA=modes_dyn,
                           AMOR_REDUIT=0.02,
                           CORR_FREQ='NON',
                           MODE_CORR=modes_sta,
                           MONO_APPUI = 'OUI',
                           EXCIT=_F( TRI_SPEC = 'OUI',
                                     SPEC_OSCI = ( spect_xy,  spect_xy, spect_xy, ),
                           ECHELLE = ( 1.,  1.,  0.5, )),
                           COMB_MODE=_F(  TYPE = 'SRSS'),
                           COMB_DIRECTION=_F(  TYPE = 'QUAD'),
                           OPTION=('EFGE_ELNO')
                          )

# résultats dépendant du temps

sismique_dyn_1 = CREA_CHAMP(TYPE_CHAM='ELNO_SIEF_R',
                            OPERATION='EXTR',
                            RESULTAT=sismique,
                            NOM_CHAM='EFGE_ELNO',
                            NUME_ORDRE=14)

sismique_qs_1 = CREA_CHAMP(TYPE_CHAM='ELNO_SIEF_R',
                            OPERATION='EXTR',
                            RESULTAT=sismique,
                            NOM_CHAM='EFGE_ELNO',
                            NUME_ORDRE=24)

# contournement car le résultat de COMB_SIMS_MODAL ne contient pas le modele
sismique_qs_1.setModel(modele)
sismique_dyn_1.setModel(modele)

sismique_dyn_2 = CREA_CHAMP(TYPE_CHAM='ELNO_SIEF_R',
                            OPERATION='ASSE',
                            MODELE=modele,
                            ASSE=_F(TOUT="OUI",
                                    CHAM_GD=sismique_dyn_1,
                                    COEF_R=0.5)
                            )

sismique_qs_2 = CREA_CHAMP(TYPE_CHAM='ELNO_SIEF_R',
                            OPERATION='ASSE',
                            MODELE=modele,
                            ASSE=_F(TOUT="OUI",
                                    CHAM_GD=sismique_qs_1,
                                    COEF_R=0.5)
                            )


sismique_total_1 = CREA_CHAMP(TYPE_CHAM='ELNO_SIEF_R',
                              OPERATION='ASSE',
                              MODELE=modele,
                              ASSE=(_F(TOUT="OUI",
                                      CHAM_GD=sismique_dyn_1,
                                      CUMUL="OUI"),
                                    _F(TOUT="OUI",
                                      CHAM_GD=sismique_qs_1,
                                      CUMUL="OUI"))
                              )

sismique_total_2 = CREA_CHAMP(TYPE_CHAM='ELNO_SIEF_R',
                              OPERATION='ASSE',
                              MODELE=modele,
                              ASSE=(_F(TOUT="OUI",
                                      CHAM_GD=sismique_dyn_2,
                                      CUMUL="OUI"),
                                    _F(TOUT="OUI",
                                      CHAM_GD=sismique_qs_2,
                                      CUMUL="OUI"))
                              )


resu_dyna=CREA_RESU(OPERATION='AFFE',
                    TYPE_RESU='DYNA_TRANS',
                    NOM_CHAM='EFGE_ELNO',
                    AFFE=(_F(CHAM_GD=sismique_dyn_1,INST=1.0,MODELE=modele),
                          _F(CHAM_GD=sismique_dyn_2,INST=2.0,MODELE=modele),
                          ),
                    )

resu_corr=CREA_RESU(OPERATION='AFFE',
                    TYPE_RESU='DYNA_TRANS',
                    NOM_CHAM='EFGE_ELNO',
                    AFFE=(_F(CHAM_GD=sismique_total_1,INST=1.0,MODELE=modele),
                          _F(CHAM_GD=sismique_total_2,INST=2.0,MODELE=modele),),
                    )

# calcul des references pour POST_ROCHE, on extrait uniquement les valeurs de MT, MFY et MFZ non nulles

table = CREA_TABLE(RESU=_F(RESULTAT=poids_propre,
                            NOM_CHAM="EFGE_ELNO",
                            TOUT="OUI",
                            NOM_CMP=("MT", "MFY", "MFZ")))
poids_propre_values = table.EXTR_TABLE().values()
mfy_poids_propre = np.array(poids_propre_values["MFY"])

table = CREA_TABLE(RESU=_F(RESULTAT=deplacement_impose,
                            NOM_CHAM="EFGE_ELNO",
                            TOUT="OUI",
                            NOM_CMP=("MT", "MFY", "MFZ")))
deplacement_impose_values = table.EXTR_TABLE().values()
mt_deplacement_impose = np.array(deplacement_impose_values["MT"])

table = CREA_TABLE(RESU=_F(RESULTAT=dilatation_thermique,
                            NOM_CHAM="EFGE_ELNO",
                            TOUT="OUI",
                            NOM_CMP=("MT", "MFY", "MFZ")))
dilatation_thermique_values = table.EXTR_TABLE().values()

table = CREA_TABLE(RESU=_F(RESULTAT=sismique,
                            NUME_ORDRE=14,
                            NOM_CHAM="EFGE_ELNO",
                            TOUT="OUI",
                            NOM_CMP=("MT", "MFY", "MFZ")))
sismique_dyn_values = table.EXTR_TABLE().values()
mfy_sismique_dyn = np.array(sismique_dyn_values["MFY"])
mfz_sismique_dyn = np.array(sismique_dyn_values["MFZ"])

table = CREA_TABLE(RESU=_F(RESULTAT=sismique,
                            NUME_ORDRE=24,
                            NOM_CHAM="EFGE_ELNO",
                            TOUT="OUI",
                            NOM_CMP=("MT", "MFY", "MFZ")))
sismique_qs_values = table.EXTR_TABLE().values()
mfy_sismique_qs = np.array(sismique_qs_values["MFY"])
mfz_sismique_qs = np.array(sismique_qs_values["MFZ"])

from sdll154a_fonctions import PostRocheAnalytic
post_roche_analytic = PostRocheAnalytic(mfy_poids_propre, mt_deplacement_impose, mfy_sismique_dyn, mfz_sismique_dyn, mfy_sismique_qs, mfz_sismique_qs)
post_roche_analytic.calcul_ressort()
post_roche_analytic.calcul_abattement()
post_roche_analytic.calcul_sigma_eq()

# appel à POST_ROCHE

resuPostRoche = POST_ROCHE(ZONE_ANALYSE=(_F(
                                     GROUP_MA='TUYAU',
                                     GROUP_NO_ORIG = 'A',
                                    ),
                                  ),
                    RESU_MECA_TRAN=(
                               _F(TYPE_CHAR='SISM_INER_TRAN',
                                 RESULTAT=resu_dyna,
                                 RESU_CORR=resu_corr,
                                 INST=(1,2),
                                 #NUME_ORDRE=(1,2),
                                 #TOUT_ORDRE='OUI',
                                 ),
                               _F(TYPE_CHAR='POIDS',
                                 RESULTAT=poids_propre,
                                 NUME_ORDRE=1,
                                 ),
                               _F(TYPE_CHAR='DILAT_THERM',
                                 RESULTAT=dilatation_thermique,
                                 NUME_ORDRE=1,
                                 ),
                               _F(TYPE_CHAR='DEPLACEMENT',
                                 RESULTAT=deplacement_impose,
                                 NUME_ORDRE=1,
                                 ),
                                ),
                     PRESSION=(_F(
                                     GROUP_MA='TUYAU',
                                     VALE = 1E6,
                                    ),
                                  ),
                    )


# TEST_RESU

TEST_RESU(RESU=(# X1 = contrainte de référence
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X1',
                   VALE_CALC=13384615.38461538,
                   VALE_REFE=post_roche_analytic._sigma_deplacement_ref[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X1',
                   VALE_CALC=13384615.38461538,
                   VALE_REFE=post_roche_analytic._sigma_deplacement_ref[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X1',
                   VALE_CALC=13384615.38461538,
                   VALE_REFE=post_roche_analytic._sigma_deplacement_ref[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X1',
                   VALE_CALC=13384615.38461538,
                   VALE_REFE=post_roche_analytic._sigma_deplacement_ref[3]),
                # X2 = contrainte de référence S2
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X2',
                   VALE_CALC=29235194.152436085,
                   VALE_REFE=post_roche_analytic._sigma_sismique_ref[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X2',
                   VALE_CALC=11392799.196481014,
                   VALE_REFE=post_roche_analytic._sigma_sismique_ref[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X2',
                   VALE_CALC=11392799.196481109,
                   VALE_REFE=post_roche_analytic._sigma_sismique_ref[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X2',
                   ORDRE_GRANDEUR=1.e6,
                   CRITERE="ABSOLU",
                   VALE_CALC=0.,
                   VALE_REFE=post_roche_analytic._sigma_sismique_ref[3]),
                # X3 = réversibilité locale t
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X3',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._t[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X3',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._t[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X3',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._t[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X3',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._t[3]),
                # X4 = réversibilité locale ts
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X4',
                   VALE_CALC=1.2090325502738972,
                   VALE_REFE=post_roche_analytic._t_s[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X4',
                   VALE_CALC=0.7547449634307279,
                   VALE_REFE=post_roche_analytic._t_s[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X4',
                   VALE_CALC=0.754744963430731,
                   VALE_REFE=post_roche_analytic._t_s[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X4',
                   VALE_CALC=0.,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._t_s[3]),
                # X5 = réversibilité totale T
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X5',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._T),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X5',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._T),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X5',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._T),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X5',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._T),
                # X6 = réversibilité totale Ts
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X6',
                   VALE_CALC=1.0603460405433702,
                   VALE_REFE=post_roche_analytic._T_s),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X6',
                   VALE_CALC=1.0603460405433702,
                   VALE_REFE=post_roche_analytic._T_s),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X6',
                   VALE_CALC=1.0603460405433702,
                   VALE_REFE=post_roche_analytic._T_s),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X6',
                   VALE_CALC=1.0603460405433702,
                   VALE_REFE=post_roche_analytic._T_s),
                # X7 = facteur d'effet de ressort r_M
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X7',
                   VALE_CALC=0.0,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._r_m[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X7',
                   VALE_CALC=0.0,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._r_m[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X7',
                   VALE_CALC=0.0,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._r_m[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X7',
                   VALE_CALC=0.0,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._r_m[3]),
                # X8 = facteur d'effet de ressort r_S
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X8',
                   VALE_CALC=0.0,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._r_s[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X8',
                   VALE_CALC=0.4049064146430583,
                   VALE_REFE=post_roche_analytic._r_s[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X8',
                   VALE_CALC=0.40490641464305255,
                   VALE_REFE=post_roche_analytic._r_s[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X8',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.,
                   VALE_REFE=post_roche_analytic._r_s[3]),
                # X9 = facteur d'effet de ressort maximal r_M_Max
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X9',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.0),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X9',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.0),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X9',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.0),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X9',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.0),
                # X10 = facteur d'effet de ressort maximal r_S_Max
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X10',
                   VALE_CALC=0.4049064146430583),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X10',
                   VALE_CALC=0.4049064146430583),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X10',
                   VALE_CALC=0.4049064146430583),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X10',
                   VALE_CALC=0.4049064146430583),
                # X11 = coefficient d'abattement g
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X11',
                   VALE_CALC=0.3788455666188711,
                   VALE_REFE=post_roche_analytic._g[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X11',
                   VALE_CALC=0.3788455666188711,
                   VALE_REFE=post_roche_analytic._g[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X11',
                   VALE_CALC=0.3788455666188711,
                   VALE_REFE=post_roche_analytic._g[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X11',
                   VALE_CALC=0.3788455666188711,
                   VALE_REFE=post_roche_analytic._g[3]),
                # X12 = coefficient d'abattement gs
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X12',
                   VALE_CALC=0.31955038357627746,
                   VALE_REFE=post_roche_analytic._g_s[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X12',
                   VALE_CALC=0.49458472195684455,
                   VALE_REFE=post_roche_analytic._g_s[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X12',
                   VALE_CALC=0.49458472195684455,
                   VALE_REFE=post_roche_analytic._g_s[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X12',
                   VALE_CALC=1.0,
                   VALE_REFE=post_roche_analytic._g_s[3]),
                # X13 = coefficient d'abattement optimisé gOpt
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X13',
                   VALE_CALC=0.3788455666188711),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X13',
                   VALE_CALC=0.3788455666188711),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X13',
                   VALE_CALC=0.3788455666188711),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X13',
                   VALE_CALC=0.3788455666188711),
                # X14 = coefficient d'abattement optimisé gsOpt
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X14',
                   VALE_CALC=0.4536387356437366),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X14',
                   VALE_CALC=0.49458472195684605),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X14',
                   VALE_CALC=0.49458472195684583),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X14',
                   VALE_CALC=1.0),
                # X15 = contrainte équivalente
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X15',
                   VALE_CALC=29148813.041733082,
                   VALE_REFE=post_roche_analytic._sigma_eq[0]),
                _F(MAILLE='M1',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X15',
                   VALE_CALC=10185687.028488198,
                   VALE_REFE=post_roche_analytic._sigma_eq[1]),
                _F(MAILLE='M2',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X15',
                   VALE_CALC=10185687.028488223,
                   VALE_REFE=post_roche_analytic._sigma_eq[2]),
                _F(MAILLE='M2',
                   POINT=2,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X15',
                   VALE_CALC=4185425.596891385,
                   VALE_REFE=post_roche_analytic._sigma_eq[3]),
                # X16 = contrainte équivalente optimisée
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X16',
                   VALE_CALC=30529848.998718902),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X16',
                   VALE_CALC=10185687.028488198),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X16',
                   VALE_CALC=10185687.02848823),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X16',
                   VALE_CALC=4185425.596891385),
                # X17 = indicateur sigmaV <sigmaP 
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X17',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X17',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X17',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X17',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                # X18 = indicateur sigmaV_s <sigmaP 
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X18',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X18',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X18',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X18',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                # X19 = indicateur sigmaV_opt <sigmaP 
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X19',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X19',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X19',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X19',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                # X20 = indicateur sigmaV_s_opt <sigmaP 
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X20',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M1',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X20',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X20',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                _F(MAILLE='M2',
                   POINT=2,
                   RESULTAT=resuPostRoche,
                   INST=1,
                   NOM_CHAM='UT01_ELNO',
                   NOM_CMP='X20',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.),
                )
        )

# maximum sur les instant

TEST_RESU(RESU=(# X1 = contrainte de référence
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X1',
                   VALE_CALC=13384615.38461538,
                   VALE_REFE=post_roche_analytic._sigma_deplacement_ref[0]),
                # X2 = contrainte de référence S2
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X2',
                   VALE_CALC=29235194.152436085,
                   VALE_REFE=post_roche_analytic._sigma_sismique_ref[0]),
                # X3 = réversibilité locale t
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X3',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._t[0]),
                # X4 = réversibilité locale ts
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X4',
                   VALE_CALC=1.2090325502738972,
                   VALE_REFE=post_roche_analytic._t_s[0]),
                # X5 = réversibilité totale T
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X5',
                   VALE_CALC=0.8180652597627946,
                   VALE_REFE=post_roche_analytic._T),
                # X6 = réversibilité totale Ts
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X6',
                   VALE_CALC=1.0603460405433702,
                   VALE_REFE=post_roche_analytic._T_s),
                # X7 = facteur d'effet de ressort r_M
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X7',
                   VALE_CALC=0.0,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._r_m[0]),
                # X8 = facteur d'effet de ressort r_S
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X8',
                   VALE_CALC=0.0,
                   ORDRE_GRANDEUR=1.,
                   VALE_REFE=post_roche_analytic._r_s[0]),
                # X9 = facteur d'effet de ressort maximal r_M_Max
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X9',
                   ORDRE_GRANDEUR=1.,
                   VALE_CALC=0.0),
                # X10 = facteur d'effet de ressort maximal r_S_Max
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X10',
                   VALE_CALC=0.404906414643059),
                # X11 = coefficient d'abattement g
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X11',
                   VALE_CALC=0.3788455666188711,
                   VALE_REFE=post_roche_analytic._g[0]),
                # X12 = coefficient d'abattement gs
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X12',
                   VALE_CALC=0.3727025965312079),
                # X13 = coefficient d'abattement optimisé gOpt
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X13',
                   VALE_CALC=0.3788455666188711),
                # X14 = coefficient d'abattement optimisé gsOpt
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X14',
                   VALE_CALC=0.48502971474540674),
                # X15 = contrainte équivalente
                _F(MAILLE='M1',
                   POINT=1,
                   REFERENCE="ANALYTIQUE",
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X15',
                   VALE_CALC=29148813.041733082,
                   VALE_REFE=post_roche_analytic._sigma_eq[0]),
                # X16 = contrainte équivalente optimisée
                _F(MAILLE='M1',
                   POINT=1,
                   RESULTAT=resuPostRoche,
                   INST=0,
                   NOM_CHAM='UT02_ELNO',
                   NOM_CMP='X16',
                   VALE_CALC=30529848.998718902,),
                )
        )

FIN()
