import code_aster
from code_aster.Commands import *

code_aster.init()

test = code_aster.TestCase()

MA = code_aster.Mesh()
MA.readMedFile("sslp100b.mmed")

MA=DEFI_GROUP(reuse=MA, MAILLAGE=MA,CREA_GROUP_NO=(
                     _F(  NOM = 'A',   NOEUD = 'N1'),
                     _F(  NOM = 'D',   NOEUD = 'N3'))
                    )

ACIER=DEFI_MATERIAU( ELAS=_F(  E = 15.,  NU = 0.3) )

CHMAT=AFFE_MATERIAU(MAILLAGE=MA,   AFFE=_F( TOUT = 'OUI', MATER = ACIER))

MO_1=AFFE_MODELE(  MAILLAGE=MA,AFFE=(

        _F( GROUP_MA = 'GRSD2',  MODELISATION = 'D_PLAN', PHENOMENE = 'MECANIQUE'),
        _F( GROUP_MA = 'GRMA14', MODELISATION = 'D_PLAN', PHENOMENE = 'MECANIQUE')))

CHBL_1=AFFE_CHAR_MECA(MODELE=MO_1,
           DDL_IMPO=_F( NOEUD = ('N8',),             DX = 0.0,   DY = 0.0)
           )

CHF1_1=AFFE_CHAR_MECA(MODELE=MO_1,
          PRES_REP=_F( GROUP_MA = ('GRMA14',), PRES = 10.0) )

CHF2_1=AFFE_CHAR_MECA(MODELE=MO_1,
          FORCE_NODALE=_F( NOEUD = ('N11',), FY = -20.0))

S_1=MACR_ELEM_STAT(
    DEFINITION=_F(  MODELE = MO_1, CHAM_MATER = CHMAT, CHAR_MACR_ELEM = CHBL_1),
      EXTERIEUR=_F(  NOEUD = ('N1','N4','N7','N10',),  GROUP_NO = ('GRNM13',)))

S_1=MACR_ELEM_STAT(reuse=S_1,
    RIGI_MECA=_F(),
    CAS_CHARGE=_F( NOM_CAS = 'CHF1', CHARGE = (CHBL_1,CHF1_1,), SUIV = 'OUI')
    )

S_1=MACR_ELEM_STAT(reuse=S_1,
    CAS_CHARGE=_F( NOM_CAS = 'CHF2', CHARGE = CHF2_1, SUIV = 'NON')
    )

MA_123=DEFI_MAILLAGE( DEFI_SUPER_MAILLE=(
      _F( MACR_ELEM = S_1, SUPER_MAILLE = 'S_1'),
      _F( MACR_ELEM = S_1, SUPER_MAILLE = 'S_2', ANGL_NAUT = (45.0,)),
      _F( MACR_ELEM = S_1, SUPER_MAILLE = 'S_3', ANGL_NAUT = (90.0,))),

    RECO_GLOBAL=_F( TOUT = 'OUI'),DEFI_NOEUD=(

    _F( TOUT = 'OUI', PREFIXE = 'NN', INDEX = (3,3,2,5,)),
               _F( NOEUD_FIN = 'N1',   SUPER_MAILLE = 'S_1', NOEUD_INIT = 'N1'),
               _F( NOEUD_FIN = 'N4',   SUPER_MAILLE = 'S_1', NOEUD_INIT = 'N4'),
               _F( NOEUD_FIN = 'N7',   SUPER_MAILLE = 'S_1', NOEUD_INIT = 'N7'),
               _F( NOEUD_FIN = 'N10',  SUPER_MAILLE = 'S_1', NOEUD_INIT = 'N10')),DEFI_GROUP_NO=(

    _F( SUPER_MAILLE = 'S_3',  GROUP_NO_FIN = 'GH', GROUP_NO_INIT = 'GRNM13'),
                  _F( SUPER_MAILLE = 'S_1',  GROUP_NO_FIN = 'AB', GROUP_NO_INIT = 'GRNM11'))
          )

MO_123=AFFE_MODELE(  MAILLAGE=MA_123,
         AFFE_SOUS_STRUC=_F(  TOUT = 'OUI'))

CHBL_123=AFFE_CHAR_MECA(MODELE=MO_123,LIAISON_DDL=(
_F( NOEUD = ('NN33', 'NN33', ),DDL = ('DY','DX',),COEF_MULT = (1.0,1.0,),COEF_IMPO = 0.0),
_F( NOEUD = ('NN36', 'NN36', ),DDL = ('DY','DX',),COEF_MULT = (1.0,1.0,),COEF_IMPO = 0.0),
_F( NOEUD = ('NN39', 'NN39', ),DDL = ('DY','DX',),COEF_MULT = (1.0,1.0,),COEF_IMPO = 0.0),
_F( NOEUD = ('NN312','NN312',),DDL = ('DY','DX',),COEF_MULT = (1.0,1.0,),COEF_IMPO = 0.0))
           )

S_123=MACR_ELEM_STAT(
    DEFINITION=_F(  MODELE = MO_123, CHAR_MACR_ELEM = CHBL_123),
    EXTERIEUR=_F(  GROUP_NO = ('GH','AB',)),
    RIGI_MECA=_F(),CAS_CHARGE=(
    _F( NOM_CAS = 'CHF1',  CHARGE = CHBL_123,  SUIV = 'OUI'),
               _F( NOM_CAS = 'CHF2',  CHARGE = CHBL_123,  SUIV = 'NON'))
    )

MAG0=DEFI_MAILLAGE(
     DEFI_SUPER_MAILLE=_F( MACR_ELEM = S_123, SUPER_MAILLE = 'S_123'),
    DEFI_NOEUD=_F( TOUT = 'OUI', INDEX = (1,0,1,8,))
          )

MAG=ASSE_MAILLAGE( MAILLAGE_1=MAG0,
                   MAILLAGE_2=MA,
                   OPERATION='SOUS_STR')

MOG=AFFE_MODELE( MAILLAGE=MAG,

       AFFE=_F( GROUP_MA = 'GRSD1', MODELISATION = 'D_PLAN', PHENOMENE = 'MECANIQUE'),
       AFFE_SOUS_STRUC=_F( SUPER_MAILLE = ('S_123',)))

CHAGBL=AFFE_CHAR_MECA(MODELE=MOG,
           DDL_IMPO=_F( NOEUD = ('N19',), DX = 2.0) )

CHAGF2=AFFE_CHAR_MECA(MODELE=MOG,
           FORCE_NODALE=_F( NOEUD = ('N15','N17',), FY = -20.0) )

CHMATG=AFFE_MATERIAU(MAILLAGE=MAG,  AFFE=_F( TOUT = 'OUI', MATER = ACIER))

MELGR=CALC_MATR_ELEM(   OPTION='RIGI_MECA',
           MODELE=MOG,  CHARGE=CHAGBL,   CHAM_MATER=CHMATG)

NUG=NUME_DDL(  MATR_RIGI=MELGR)                 

MATAS=ASSE_MATRICE(   NUME_DDL=NUG,  MATR_ELEM=MELGR)

MATAS=FACTORISER( reuse=MATAS, MATR_ASSE=MATAS,    METHODE='LDLT')

VELG1=CALC_VECT_ELEM(    OPTION='CHAR_MECA',
          CHARGE=CHAGBL,
           MODELE=MOG, SOUS_STRUC=_F( CAS_CHARGE = 'CHF1', SUPER_MAILLE = 'S_123')
               )

VECAS1=ASSE_VECTEUR(   NUME_DDL=NUG,  VECT_ELEM=VELG1)

U1=RESOUDRE( MATR=MATAS,   CHAM_NO=VECAS1)

U1S_123=DEPL_INTERNE(   DEPL_GLOBAL=U1,    SUPER_MAILLE='S_123',
                            NOM_CAS='CHF1' )

test.assertTrue( True )

FIN()
