# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2018 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

# person_in_charge: mickael.abbas at edf.fr

"""Ce module définit les noms de variables internes valides.
Un comportement ne doit/peut pas utiliser une variable internes dont le
nom ne serait pas déclaré ici."""

DICT_NOM_VARI = {
    "AAAR": _(u"FLUA_ENDO_PORO avancement AAR"),
    "ADEF": _(u"FLUA_ENDO_PORO avancement DEF"),
    "ADOUCOMP": _(u"affaiblissement relatif de raideur en membrane en compression"),
    "ADOUFLEX": _(u"affaiblissement relatif de raideur en flexion"),
    "ADOUMEMB": _(u"affaiblissement relatif de raideur en membrane"),
    "ADOUTRAC": _(u"affaiblissement relatif de raideur en membrane en traction"),
    "AFM1": _(u"FLUA_ENDO_PORO sulfo aluminates pour la def"),
    "AFM2": _(u"FLUA_ENDO_PORO sulfo aluminates pour la def"),
    "AFT1": _(u"FLUA_ENDO_PORO sulfo aluminates pour la def"),
    "AFT2": _(u"FLUA_ENDO_PORO sulfo aluminates pour la def"),
    "ALEA": _(u"contrainte de rupture par amorçage,"),
    "ALPHA2XX": _(u"écrouissage cinématique non linéaire variable interne 2  composante XX"),
    "ALPHA2XY": _(u"écrouissage cinématique non linéaire variable interne 2  composante XY"),
    "ALPHA2XZ": _(u"écrouissage cinématique non linéaire variable interne 2  composante XZ"),
    "ALPHA2YY": _(u"écrouissage cinématique non linéaire variable interne 2  composante YY"),
    "ALPHA2YZ": _(u"écrouissage cinématique non linéaire variable interne 2  composante YZ"),
    "ALPHA2ZZ": _(u"écrouissage cinématique non linéaire variable interne 2  composante ZZ"),
    "ALPHAXX": _(u"écrouissage cinématique non linéaire variable interne 1  composante XX"),
    "ALPHAXY": _(u"écrouissage cinématique non linéaire variable interne 1  composante XY"),
    "ALPHAXZ": _(u"écrouissage cinématique non linéaire variable interne 1  composante XZ"),
    "ALPHAYY": _(u"écrouissage cinématique non linéaire variable interne 1  composante YY"),
    "ALPHAYZ": _(u"écrouissage cinématique non linéaire variable interne 1  composante YZ"),
    "ALPHAZZ": _(u"écrouissage cinématique non linéaire variable interne 1  composante ZZ"),
    "ANGL1": _(u"GLRC_DAMAGE : angle d'orthotropie 1"),
    "ANGL2": _(u"GLRC_DAMAGE : angle d'orthotropie 2"),
    "ANGL3": _(u"GLRC_DAMAGE : angle d'orthotropie 3"),
    "ANGLEDEV": _(u"angle du seuil déviatoire (CJS)"),
    "ASSCORN1": _(u"assemblage cornière, variable interne 1"),
    "ASSCORN2": _(u"assemblage cornière, variable interne 2"),
    "ASSCORN3": _(u"assemblage cornière, variable interne 3"),
    "ASSCORN4": _(u"assemblage cornière, variable interne 4"),
    "ASSCORN5": _(u"assemblage cornière, variable interne 5"),
    "ASSCORN6": _(u"assemblage cornière, variable interne 6"),
    "ASSCORN7": _(u"assemblage cornière, variable interne 7"),
    "ATIL": _(u"FLUA_ENDO_PORO sulfo aluminates pour la def"),
    "AUSTENITE": _(u"phase métallurgique acier variable (austenite)"),
    "BAINITE": _(u"phase métallurgique acier variable (bainite)"),
    "BIOG": _(u"FLUA_ENDO_PORO coeff de Biot effectif pour les RGI"),
    "BIOW": _(u"FLUA_ENDO_PORO coeff de Biot effectif pour la capillarite"),
    "BR_AVCHI": _(u"BETON_RAG : Avancement chimique"),
    "BR_DVRAG1":_(u"BETON_RAG : Endommagement dû à la RAG, composante 1"),
    "BR_DVRAG2":_(u"BETON_RAG : Endommagement dû à la RAG, composante 1"),
    "BR_DVRAG3":_(u"BETON_RAG : Endommagement dû à la RAG, composante 1"),
    "BR_EFU11": _(u"BETON_RAG : déformation déviatorique de fluage, composante 1"),
    "BR_EFU12": _(u"BETON_RAG : déformation déviatorique de fluage, composante 4"),
    "BR_EFU13": _(u"BETON_RAG : déformation déviatorique de fluage, composante 5"),
    "BR_EFU22": _(u"BETON_RAG : déformation déviatorique de fluage, composante 2"),
    "BR_EFU23": _(u"BETON_RAG : déformation déviatorique de fluage, composante 6"),
    "BR_EFU33": _(u"BETON_RAG : déformation déviatorique de fluage, composante 3"),
    "BR_EFUSP": _(u"BETON_RAG : déformation sphérique de fluage"),
    "BR_EP111": _(u"BETON_RAG : déformation déviatorique de fluage interne modèle, composante 1"),
    "BR_EP112": _(u"BETON_RAG : déformation déviatorique de fluage interne modèle, composante 4"),
    "BR_EP113": _(u"BETON_RAG : déformation déviatorique de fluage interne modèle, composante 5"),
    "BR_EP122": _(u"BETON_RAG : déformation déviatorique de fluage interne modèle, composante 2"),
    "BR_EP123": _(u"BETON_RAG : déformation déviatorique de fluage interne modèle, composante 6"),
    "BR_EP133": _(u"BETON_RAG : déformation déviatorique de fluage interne modèle, composante 3"),
    "BR_EP1SP": _(u"BETON_RAG : déformation sphérique de fluage interne modèle"),
    "BR_EPV11": _(u"BETON_RAG : Déformation viscoplastique de la RAG, composante 1"),
    "BR_EPV12": _(u"BETON_RAG : Déformation viscoplastique de la RAG, composante 4"),
    "BR_EPV13": _(u"BETON_RAG : Déformation viscoplastique de la RAG, composante 5"),
    "BR_EPV22": _(u"BETON_RAG : Déformation viscoplastique de la RAG, composante 2"),
    "BR_EPV23": _(u"BETON_RAG : Déformation viscoplastique de la RAG, composante 6"),
    "BR_EPV33": _(u"BETON_RAG : Déformation viscoplastique de la RAG, composante 3"),
    "BR_ETUDE": _(u"BETON_RAG : Niveau des études réalisées"),
    "BR_PRGEL": _(u"BETON_RAG : Pression du gel"),
    "BR_SIGDP": _(u"BETON_RAG : contrainte seuil d'endommagement de compression"),
    "BR_SUT11": _(u"BETON_RAG : contrainte seuil d'endommagement de traction, composante 1"),
    "BR_SUT12": _(u"BETON_RAG : contrainte seuil d'endommagement de traction, composante 4"),
    "BR_SUT13": _(u"BETON_RAG : contrainte seuil d'endommagement de traction, composante 5"),
    "BR_SUT22": _(u"BETON_RAG : contrainte seuil d'endommagement de traction, composante 2"),
    "BR_SUT23": _(u"BETON_RAG : contrainte seuil d'endommagement de traction, composante 6"),
    "BR_SUT33": _(u"BETON_RAG : contrainte seuil d'endommagement de traction, composante 3"),
    "COHESION": _(u"cohésion"),
    "COMPT": _(u"itération de Newton courante,"),
    "COMR": _(u"itération de Newton de rupture,"),
    "CRITEPS": _(u"Critère en déformation, utilisé en Génie Civil"),
    "CRITHILL": _(u"Critère de Hill : pour Hujeux : densité normalisée pour le travail du second ordre"),
    "CRITRUPT": _(u"Critère de rupture pour CRIT_RUPT"),
    "CRITSIG": _(u"Critère en contrainte, utilisé en Génie Civil"),
    "CSHR": _(u"FLUA_ENDO_PORO perte de viscosité par séchage (coeff de consolidation par séchage)"),
    "DB1": _(u"c_plan ou 1d algo Deborst, variable interne 1"),
    "DB2": _(u"c_plan ou 1d algo Deborst, variable interne 2"),
    "DB3": _(u"c_plan ou 1d algo Deborst, variable interne 3"),
    "DB4": _(u"c_plan ou 1d algo Deborst, variable interne 4"),
    "DCG1": _(u"FLUA_ENDO_PORO endommagements principaux de compression difffus RGI"),
    "DCG2": _(u"FLUA_ENDO_PORO endommagements principaux de compression difffus RGI"),
    "DCG3": _(u"FLUA_ENDO_PORO endommagements principaux de compression difffus RGI"),
    "DC": _(u"FLUA_ENDO_PORO endommagement de compression"),
    "DDISSM": _(u"Vitesse de dissipation mécanique"),
    "DEPLANEX": _(u"DIS_ECRO_TRAC : Déplacement anélastique, suivant x local."),
    "DEPLCUMX": _(u"DIS_ECRO_TRAC : Déplacement anélastique cumulé, suivant x local."),
    "DEPLX": _(u"DIS_ECRO_TRAC : Déplacement différentiel, suivant x local."),
    "DEPPLAS1": _(u"JOINT_MECA_FROT  déplacement tangentiel plastique par rapport au point de départ, composante 1"),
    "DEPPLAS2": _(u"JOINT_MECA_FROT  déplacement tangentiel plastique par rapport au point de départ, composante 2"),
    "DEPSPEQ": _(u"incrément de déformation plastique équivalente"),
    "DEPS-TH": _(u"PINTO-MENEGOTTO V5"),
    "DETOPTG": _(u"Hujeux : déterminant de la matrice tangente"),
    "DFLU": _(u"FLUA_ENDO_PORO endomagement par fluage"),
    "DINSTM": _(u"Incrément de temps"),
    "DIS10": _(u"éléments discrets, variable interne 10"),
    "DIS11": _(u"éléments discrets, variable interne 11"),
    "DIS12": _(u"éléments discrets, variable interne 12"),
    "DIS13": _(u"éléments discrets, variable interne 13"),
    "DIS14": _(u"éléments discrets, variable interne 14"),
    "DIS15": _(u"éléments discrets, variable interne 15"),
    "DIS16": _(u"éléments discrets, variable interne 16"),
    "DIS17": _(u"éléments discrets, variable interne 17"),
    "DIS18": _(u"éléments discrets, variable interne 18"),
    "DIS1": _(u"éléments discrets, variable interne 1"),
    "DIS2": _(u"éléments discrets, variable interne 2"),
    "DIS3": _(u"éléments discrets, variable interne 3"),
    "DIS4": _(u"éléments discrets, variable interne 4"),
    "DIS5": _(u"éléments discrets, variable interne 5"),
    "DIS6": _(u"éléments discrets, variable interne 6"),
    "DIS7": _(u"éléments discrets, variable interne 7"),
    "DIS8": _(u"éléments discrets, variable interne 8"),
    "DIS9": _(u"éléments discrets, variable interne 9"),
    "DISSENDO": _(u"dissipation d'endommagement"),
    "DISSGLIS": _(u"dissipation de glissement"),
    "DISSIP": _(u"dissipation plastique"),
    "DISSTHER": _(u"dissipation Thermodynamique"),
    "DISTSDEV": _(u"CJS distance normalisée au seuil déviatoire"),
    "DISTSISO": _(u"CJS distance normalisée au seuil isotrope"),
    "DOMAINE": _(u"domaine de comportement de la roche"),
    "DOMCOMP": _(u"Laigle : domaine de comportement de la roche"),
    "DRL1": _(u"FLUA_ENDO_PORO endommagements principaux de refermeture"),
    "DRL2": _(u"FLUA_ENDO_PORO endommagements principaux de refermeture"),
    "DRL3": _(u"FLUA_ENDO_PORO endommagements principaux de refermeture"),
    "DSW1": _(u"FLUA_ENDO_PORO Cumul des surpessions capillaires en dessiccation sous charge"),
    "DSW2": _(u"FLUA_ENDO_PORO Cumul des surpessions capillaires en dessiccation sous charge"),
    "DSW3": _(u"FLUA_ENDO_PORO Cumul des surpessions capillaires en dessiccation sous charge"),
    "DSW4": _(u"FLUA_ENDO_PORO Cumul des surpessions capillaires en dessiccation sous charge"),
    "DSW5": _(u"FLUA_ENDO_PORO Cumul des surpessions capillaires en dessiccation sous charge"),
    "DSW6": _(u"FLUA_ENDO_PORO Cumul des surpessions capillaires en dessiccation sous charge"),
    "DTG1": _(u"FLUA_ENDO_PORO endommagements principaux de traction diffus RGI"),
    "DTG2": _(u"FLUA_ENDO_PORO endommagements principaux de traction diffus RGI"),
    "DTG3": _(u"FLUA_ENDO_PORO endommagements principaux de traction diffus RGI"),
    "DTHE": _(u"FLUA_ENDO_PORO endommagement thermique isotrope"),
    "DTHE": _(u"endommagement thermique"),
    "DTL1": _(u"FLUA_ENDO_PORO endommagements principaux de traction directe "),
    "DTL1": _(u"densite de fissuration diffuse de traction"),
    "DTL2": _(u"FLUA_ENDO_PORO endommagements principaux de traction directe "),
    "DTL2": _(u"densite de fissuration diffuse de traction"),
    "DTL3": _(u"FLUA_ENDO_PORO endommagements principaux de traction directe "),
    "DTL3": _(u"densite de fissuration diffuse de traction"),
    "DTPP": _(u"FLUA_ENDO_PORO endommagement de traction diffus pre pic"),
    "DUY": _(u"valeur maximale de la différence déplacement local-déplacement limite"),
    "EBLOC": _(u"énergie bloquée"),
    "ECRISOM1": _(u"JOINT_BA : variable scalaire de l'écrouissage isotrope pour l'endommagement en mode 1"),
    "ECRISOM2": _(u"JOINT_BA : variable scalaire de l'écrouissage isotrope pour l'endommagement en mode 2"),
    "ECROCINE": _(u"JOINT_BA : valeur de l'écrouissage cinématique par frottement des fissures"),
    "ECROISOT": _(u"Variable d'écrouissage isotrope"),
    "EDISSCUM": _(u"énergie dissipée cumulée à chaque pas pour CRIT_RUPT"),
    "EDISS": _(u"énergie dissipée pour CRIT_RUPT"),
    "EFD11": _(u"retrait de dessiccation, composante 11"),
    "EFD12": _(u"retrait de dessiccation, composante 12"),
    "EFD22": _(u"retrait de dessiccation, composante 22"),
    "EFD23": _(u"retrait de dessiccation, composante 23"),
    "EFD31": _(u"retrait de dessiccation, composante 31"),
    "EFD33": _(u"retrait de dessiccation, composante 33"),
    "EID11": _(u"déformation déviatorique irréversible, composante 11"),
    "EID12": _(u"déformation déviatorique irréversible, composante 12"),
    "EID22": _(u"déformation déviatorique irréversible, composante 22"),
    "EID23": _(u"déformation déviatorique irréversible, composante 23"),
    "EID31": _(u"déformation déviatorique irréversible, composante 31"),
    "EID33": _(u"déformation déviatorique irréversible, composante 33"),
    "EISP": _(u"déformation sphérique irréversible"),
    "ELEP1": _(u"numéro de l'élément pointé numéro 1,"),
    "ELEP2": _(u"numéro de l'élément pointé numéro 2 (quand amorçage),"),
    "EMT1": _(u"FLUA_ENDO_PORO deformation plastique maximale atteinte en traction"),
    "EMT2": _(u"FLUA_ENDO_PORO deformation plastique maximale atteinte en traction"),
    "EMT3": _(u"FLUA_ENDO_PORO deformation plastique maximale atteinte en traction"),
    "EMT4": _(u"FLUA_ENDO_PORO deformation plastique maximale atteinte en traction"),
    "EMT5": _(u"FLUA_ENDO_PORO deformation plastique maximale atteinte en traction"),
    "EMT6": _(u"FLUA_ENDO_PORO deformation plastique maximale atteinte en traction"),
    "ENDOCOMP": _(u"endommagement scalaire en compression"),
    "ENDOFL-": _(u"variable d'endommagement pour la flexion négative"),
    "ENDOFL+": _(u"variable d'endommagement pour la flexion positive"),
    "ENDOINF": _(u"variable d'endommagement pour la moitié inférieure de la plaque"),
    "ENDONOR": _(u"endommagement normal"),
    "ENDORIGI": _(u"rigidité résiduelle"),
    "ENDOSUP": _(u"variable d'endommagement pour la moitié supérieure de la plaque"),
    "ENDOTAN": _(u"endommagement tangentiel"),
    "ENDO": _(u"endommagement scalaire"),
    "ENDOXX": _(u"tenseur endommagement, direction XX"),
    "ENDOXY": _(u"tenseur endommagement, direction XY"),
    "ENDOXZ": _(u"tenseur endommagement, direction XZ"),
    "ENDOYY": _(u"tenseur endommagement, direction YY"),
    "ENDOYZ": _(u"tenseur endommagement, direction YZ"),
    "ENDOZZ": _(u"tenseur endommagement, direction ZZ"),
    "ENEL_RES": _(u"énergie résiduelle"),
    "EPAISSJO": _(u"épaisseur du joint clavé"),
    "EPC1": _(u"FLUA_ENDO_PORO defromations plastiques de druker prager"),
    "EPC2": _(u"FLUA_ENDO_PORO defromations plastiques de druker prager"),
    "EPC3": _(u"FLUA_ENDO_PORO defromations plastiques de druker prager"),
    "EPC4": _(u"FLUA_ENDO_PORO defromations plastiques de druker prager"),
    "EPC5": _(u"FLUA_ENDO_PORO defromations plastiques de druker prager"),
    "EPC6": _(u"FLUA_ENDO_PORO defromations plastiques de druker prager"),
    "EPE1": _(u"FLUA_ENDO_PORO  deformations elastiques"),
    "EPE2": _(u"FLUA_ENDO_PORO  deformations elastiques"),
    "EPE3": _(u"FLUA_ENDO_PORO deformations elastiques"),
    "EPE4": _(u"FLUA_ENDO_PORO deformations elastiques"),
    "EPE5": _(u"FLUA_ENDO_PORO deformations elastiques"),
    "EPE6": _(u"FLUA_ENDO_PORO deformations elastiques"),
    "EPEQIRRA": _(u"déformation plastique équivalente d'irradiation"),
    "EPG1": _(u"FLUA_ENDO_PORO deformation plastique fissuration rgi"),
    "EPG2": _(u"FLUA_ENDO_PORO deformation plastique fissuration rgi"),
    "EPG3": _(u"FLUA_ENDO_PORO deformation plastique fissuration rgi"),
    "EPG4": _(u"FLUA_ENDO_PORO deformation plastique fissuration rgi"),
    "EPG5": _(u"FLUA_ENDO_PORO deformation plastique fissuration rgi"),
    "EPG6": _(u"FLUA_ENDO_PORO deformation plastique fissuration rgi"),
    "EPK1": _(u"FLUA_ENDO_PORO deformation de l etage de Kelvin"),
    "EPK2": _(u"FLUA_ENDO_PORO deformation de l etage de Kelvin"),
    "EPK3": _(u"FLUA_ENDO_PORO deformation de l etage de Kelvin"),
    "EPK4": _(u"FLUA_ENDO_PORO deformation de l etage de Kelvin"),
    "EPK5": _(u"FLUA_ENDO_PORO deformation de l etage de Kelvin"),
    "EPK6": _(u"FLUA_ENDO_PORO deformation de l etage de Kelvin"),
    "EPLC": _(u"FLUA_ENDO_PORO deformation plastique equivalente en cisaillement"),
    "EPM1": _(u"FLUA_ENDO_PORO deformations de l etage de Maxwell"),
    "EPM2": _(u"FLUA_ENDO_PORO deformations de l etage de Maxwell"),
    "EPM3": _(u"FLUA_ENDO_PORO deformations de l etage de Maxwell"),
    "EPM4": _(u"FLUA_ENDO_PORO deformations de l etage de Maxwell"),
    "EPM5": _(u"FLUA_ENDO_PORO deformations de l etage de Maxwell"),
    "EPM6": _(u"FLUA_ENDO_PORO deformations de l etage de Maxwell"),
    "EPSEDXX": _(u"déformation élastique endommagée composante XX"),
    "EPSEDXX": _(u"déformation élastique endommagée composante XX"),
    "EPSEDXY": _(u"déformation élastique endommagée composante XY"),
    "EPSEDXY": _(u"déformation élastique endommagée composante XY"),
    "EPSEDXZ": _(u"déformation élastique endommagée composante XZ"),
    "EPSEDXZ": _(u"déformation élastique endommagée composante XZ"),
    "EPSEDYY": _(u"déformation élastique endommagée composante YY"),
    "EPSEDYY": _(u"déformation élastique endommagée composante YY"),
    "EPSEDYZ": _(u"déformation élastique endommagée composante YZ"),
    "EPSEDYZ": _(u"déformation élastique endommagée composante YZ"),
    "EPSEDZZ": _(u"déformation élastique endommagée composante ZZ"),
    "EPSEDZZ": _(u"déformation élastique endommagée composante ZZ"),
    "EPSEQC": _(u"déformation de compression équivalente, au sens de Mazars"),
    "EPSEQT": _(u"déformation de traction équivalente, au sens de Mazars"),
    "EPSEQ": _(u"déformation équivalente, au sens de Mazars"),
    "EPSEXX": _(u"déformation élastique composante XX"),
    "EPSEXY": _(u"déformation élastique composante XY"),
    "EPSEXZ": _(u"déformation élastique composante XZ"),
    "EPSEYY": _(u"déformation élastique composante YY"),
    "EPSEYZ": _(u"déformation élastique composante YZ"),
    "EPSEZZ": _(u"déformation élastique composante ZZ"),
    "EPSGRD": _(u"déformation de grandissement."),
    "EPSM+V5": _(u" Pinto-Menegotto, déformation totale"),
    "EPSP1": _(u"GLRC_DAMAGE : extension membranaire plastique 1"),
    "EPSP2": _(u"GLRC_DAMAGE : extension membranaire plastique 2"),
    "EPSP3": _(u"GLRC_DAMAGE : extension membranaire plastique 3"),
    "EPSPEQC": _(u"déformation plastique équivalente (déviatorique)  cumulée en compression"),
    "EPSPEQT": _(u"déformation plastique équivalente (déviatorique)  cumulée en traction"),
    "EPSPEQ": _(u"déformation plastique équivalente (déviatorique)  cumulée"),
    "EPSPVIT": _(u"Vitesse de déformation plastique mécanique"),
    "EPSPVOL": _(u"déformation plastique équivalente volumique"),
    "EPSPXX": _(u"déformation plastique composante XX"),
    "EPSPXY": _(u"déformation plastique composante XY"),
    "EPSPXZ": _(u"déformation plastique composante XZ"),
    "EPSPYY": _(u"déformation plastique composante YY"),
    "EPSPYZ": _(u"déformation plastique composante YZ"),
    "EPSPZZ": _(u"déformation plastique composante ZZ"),
    "EPSRN-1": _(u"déformation du cycle précédent  Pinto-Menegotto"),
    "EPSRN": _(u"déformation du cycle actuel, Pinto-Menegotto"),
    "EPSRN": _(u"déformation du cycle actuel, Pinto-Menegotto"),
    "EPSVOLME" : _(u"déformations volumiques élastiques mécaniques"),
    "EPSVOLME" : _(u"déformations volumiques élastiques mécaniques"),
    "EPSVOLTH" : _(u"déformations volumiques élastiques thermiques"),
    "EPSVOLTH" : _(u"déformations volumiques élastiques thermiques"),
    "EPSVOLVP" : _(u"déformations volumiques viscoplastiques"),
    "EPSVOLVP" : _(u"déformations volumiques viscoplastiques"),
    "EPT1": _(u"FLUA_ENDO_PORO deformation plastique de traction "),
    "EPT2": _(u"FLUA_ENDO_PORO deformation plastique de traction "),
    "EPT3": _(u"FLUA_ENDO_PORO deformation plastique de traction "),
    "EPT4": _(u"FLUA_ENDO_PORO deformation plastique de traction "),
    "EPT5": _(u"FLUA_ENDO_PORO deformation plastique de traction "),
    "EPT6": _(u"FLUA_ENDO_PORO deformation plastique de traction "),
    "ERD11": _(u"déformation déviatorique réversible, composante 11"),
    "ERD11": _(u"déformation déviatorique réversible, composante 11"),
    "ERD12": _(u"déformation déviatorique réversible, composante 12"),
    "ERD12": _(u"déformation déviatorique réversible, composante 12"),
    "ERD22": _(u"déformation déviatorique réversible, composante 22"),
    "ERD22": _(u"déformation déviatorique réversible, composante 22"),
    "ERD23": _(u"déformation déviatorique réversible, composante 23"),
    "ERD23": _(u"déformation déviatorique réversible, composante 23"),
    "ERD31": _(u"déformation déviatorique réversible, composante 31"),
    "ERD31": _(u"déformation déviatorique réversible, composante 31"),
    "ERD33": _(u"déformation déviatorique réversible, composante 33"),
    "ERD33": _(u"déformation déviatorique réversible, composante 33"),
    "ERSP": _(u"Déformation sphérique réversible"),
    "FECRDVC1": _(u"Hujeux : facteur de mobilisation du mécanisme déviatoire cyclique, k= 1"),
    "FECRDVC2": _(u"Hujeux : facteur de mobilisation du mécanisme déviatoire cyclique, k= 1"),
    "FECRDVC3": _(u"Hujeux : facteur de mobilisation du mécanisme déviatoire cyclique, k= 1"),
    "FECRDVM1": _(u"Hujeux : facteur de mobilisation du mécanisme déviatoire monotone, k= 1"),
    "FECRDVM2": _(u"Hujeux : facteur de mobilisation du mécanisme déviatoire monotone, k= 2"),
    "FECRDVM3": _(u"Hujeux : facteur de mobilisation du mécanisme déviatoire monotone, k= 3"),
    "FECRISC1": _(u"Hujeux : facteur de mobilisation du mécanisme de consolidation cyclique"),
    "FECRISM1": _(u"Hujeux : facteur de mobilisation du mécanisme de consolidation monotone"),
    "FERRITE": _(u"phase métallurgique acier variable (ferrite)"),
    "FH_X": _(u"flux hydraulique dans le repère global ( xxx_JOINT_HYME) composante 1"),
    "FH_Y": _(u"flux hydraulique dans le repère global ( xxx_JOINT_HYME) composante 2"),
    "FH_Z": _(u"flux hydraulique dans le repère global ( xxx_JOINT_HYME) composante 3"),
    "FORCE": _(u"Force"),
    "GAMMAECR": _(u"le paramètre d'écrouissage correspondant à la déformation irréversible majeure."),
    "GAMMAP": _(u"déformation déviatorique plastique"),
    "GAMMAVP": _(u"déformation déviatorique viscoplastique"),
    "GLIS": _(u"JOINT_BA : déformation de glissement cumulée par frottement des fissures"),
    "GLISXINF": _(u"DHRC : déformation de glissement le long des aciers orientés selon X dans la partie inférieure de la plaque"),
    "GLISXSUP": _(u"DHRC : déformation de glissement le long des aciers orientés selon X dans la partie supérieure de la plaque"),
    "GLISYINF": _(u"DHRC : déformation de glissement le long des aciers orientés selon Y dans la partie inférieure de la plaque"),
    "GLISYSUP": _(u"DHRC : déformation de glissement le long des aciers orientés selon Y dans la partie supérieure de la plaque"),
    "GONF": _(u"gonflement"),
    "GR1": _(u"elas_poutre_GR v1"),
    "GR2": _(u"elas_poutre_GR v2"),
    "GR3": _(u"elas_poutre_GR v3"),
    "GRADP_X": _(u"gradient de pression dans le repère global ( xxx_JOINT_HYME)  Composante 1"),
    "GRADP_Y": _(u"gradient de pression dans le repère global ( xxx_JOINT_HYME)  Composante 2"),
    "GRADP_Z": _(u"gradient de pression dans le repère global ( xxx_JOINT_HYME)  Composante 3"),
    "H1": _(u"Hayhurst : variable d'écrouissage H1"),
    "H2": _(u"Hayhurst : variable d'écrouissage H2"),
    "HIS10": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 1, composante 2"),
    "HIS11": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 1, composante 3"),
    "HIS12": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 1, composante 4"),
    "HIS13": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 2, composante 1"),
    "HIS14": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 2, composante 2"),
    "HIS15": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 2, composante 3"),
    "HIS16": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 2, composante 4"),
    "HIS17": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 3, composante 1"),
    "HIS18": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 3, composante 2"),
    "HIS19": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 3, composante 3"),
    "HIS20": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 3, composante 4"),
    "HIS21": _(u"Hujeux : variable mémoratrice discontinue du mécanisme de consolidation"),
    "HIS22": _(u"Hujeux : variable mémoratrice discontinue de normale à la surface de charge du mécanisme de consolidation"),
    "HIS34": _(u"Hujeux : Indicateur d'état des mécanismes actifs après convergence"),
    "HIS9": _(u"Hujeux : variable mémoratrice pour le mécanisme déviatoire cyclique du plan 1, composante 1"),
    "HYDF": _(u"FLUA_ENDO_PORO hydratation fin de pas"),
    "INDETAC1": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes cycliques, composante 1"),
    "INDETAC2": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes cycliques, composante 2"),
    "INDETAC3": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes cycliques, composante 3"),
    "INDETAC4": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes cycliques, composante 4"),
    "INDETAM1": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes monotones ou de passage au cyclique, composante 1"),
    "INDETAM2": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes monotones ou de passage au cyclique, composante 2"),
    "INDETAM3": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes monotones ou de passage au cyclique, composante 3"),
    "INDETAM4": _(u"Hujeux : indicateur d'activation (1) ou non (0) des mécanismes monotones ou de passage au cyclique, composante 4"),
    "INDICDIL": _(u"indicateur de contractance ou de dilatance"),
    "INDIC": _(u"LETK : indicateur de la position de l'etat de contrainte par rapport aux seuils viscoplastiques"),
    "INDICYCL": _(u" Pinto-Menegotto, indicateur d'activation du comportement cyclique"),
    "INDIDISS": _(u"Indicateur de dissipation =0 si régime linéaire, =1 si régime dissipatif."),
    "INDIEND1": _(u"indicateur d'endommagement pour la flexion positive"),
    "INDIEND2": _(u"indicateur d'endommagement pour la flexion négative"),
    "INDIENDN": _(u"indicateur d'endommagement normal =0 sain, =1 endommagé, =2 cassé"),
    "INDIENDO": _(u"indicateur d'endommagement"),
    "INDIENDT": _(u"indicateur d'endommagement tangentiel =0 sain, =1 endommagé, =2 cassé"),
    "INDIFLAM": _(u"indicateur de flambement"),
    "INDIHYDR": _(u"indicateur d'irréversibilité hydrique"),
    "INDIOUV": _(u"JOINT_MECA_FROT : indicateur d'ouverture complète =0 fermé, =1 ouvert"),
    "INDIPLAC": _(u"indicateur de plasticité en compression  (0 : seuil non atteint, 1 ou > 1 : seuil atteint)"),
    "INDIPLAS": _(u"indicateur de plasticité (0 : seuil non atteint, 1 ou > 1 : seuil atteint)"),
    "INDIPLAT": _(u"indicateur de plasticité en traction  (0 : seuil non atteint, 1 ou > 1 : seuil atteint)"),
    "INDIVIDE": _(u"indice des vides"),
    "INDIVISC": _(u"indicateur de viscoplasticité"),
    "IRRA": _(u"irradiation"),
    "IRVECU": _(u"mémorisation de l'historique d'irradiation (fluence),"),
    "ISPH": _(u"BETON_UMLV : v21"),
    "KHIP1": _(u"GLRC_DAMAGE : courbure plastique 1"),
    "KHIP2": _(u"GLRC_DAMAGE : courbure plastique 2"),
    "KHIP3": _(u"GLRC_DAMAGE : courbure plastique 3"),
    "KSIXX": _(u"tenseur de rappel pour l'effet de mémoire, composante XX"),
    "KSIXY": _(u"tenseur de rappel pour l'effet de mémoire, composante XY"),
    "KSIXZ": _(u"tenseur de rappel pour l'effet de mémoire, composante XZ"),
    "KSIYY": _(u"tenseur de rappel pour l'effet de mémoire, composante YY"),
    "KSIYZ": _(u"tenseur de rappel pour l'effet de mémoire, composante YZ"),
    "KSIZZ": _(u"tenseur de rappel pour l'effet de mémoire, composante ZZ"),
    "LAMBDA": _(u"JOINT_MECA_FROT : paramètre croissant indiquant le déplacement tangentiel plastique cumulé (sans orientation)."),
    "MARTENSITE": _(u"phase métallurgique acier variable (martensite)"),
    "MEMOECRO": _(u"CIN2_MEMO : variable relative à la mémoire d'écrouissage q"),
    "NBITER": _(u"nombre d'itérations internes"),
    "NBSSPAS": _(u"nombre de redécoupages locaux du pas de temps"),
    "PCENDOT": _(u"pourcentage d'endommagement tangentiel"),
    "PCENERDI": _(u"pourcentage d'endommagement normal (dans la zone adoucissante)"),
    "PCR": _(u"pression critique"),
    "PDISSCUM": _(u"puissance dissipée cumulée à chaque pas pour CRIT_RUPT"),
    "PDISS": _(u"puissance dissipée pour CRIT_RUPT"),
    "PERLITE": _(u"phase métallurgique acier variable (perlite)"),
    "PERM_LONG": _(u"perméabilité longitudinale de la fissure"),
    "PHIG": _(u"FLUA_ENDO_PORO potentiel des phases neoformees"),
    "PHIM": _(u"FLUA_ENDO_PORO dissipation etage de Maxwell"),
    "PHI": _(u"Hayhurst : variable PHI"),
    "POROSITE": _(u"Porosité"),
    "POS": _(u"VISC_DRUC_PRAG : position du point de charge par rapport au seuil"),
    "PPAS": _(u"FLUA_ENDO_PORO indicateur premier pas (1 si premier pas passé sinon 0)"),
    "PRE1": _(u"Pression capillaire"),
    "PRE2": _(u"Pression du gaz"),
    "PRESF": _(u"pression de fluide"),
    "PRGI": _(u"FLUA_ENDO_PORO pression de RGI"),
    "PSHR": _(u"FLUA_ENDO_PORO pression capillaire de l eau"),
    "PVP": _(u"Pression de vapeur"),
    "RAIDEUR": _(U"DIS_ZENER, DIS_ECRO_TRAC : Raideur du discret"),
    "RESIDU": _(u"valeur du test local d'arrêt des itérations internes"),
    "RHOLIQ": _(u"Masse volumique du liquide"),
    "RHXZ": _(u"Hujeux : rayon du seuil déviatoire atteint par  la surface de charge avant le décharge du mécanisme déviatoire du plan 2"),
    "RHYZ": _(u"Hujeux : rayon du seuil déviatoire atteint par  la surface de charge avant le décharge du mécanisme déviatoire du plan 1"),
    "RSIGMA": _(u"Facteur de triaxialité des contraintes, modèle Mazars"),
    "SATLIQ": _(u"Saturation"),
    "SAUT_N": _(u"saut normal"),
    "SAUT_T1": _(u"saut tangentiel 1"),
    "SAUT_T2": _(u"saut tangentiel 2"),
    "SDEVCRIT": _(u"CJS rapport entre le seuil déviatoire et le seuil déviatorique critique"),
    "SDEVEPSP": _(u"CJS signe du produit contracté de la contrainte déviatorique par la déformation plastique déviatorique"),
    "SEUILDEP": _(u"CZM  seuil correspondant au plus grand saut de déplacement (en norme)"),
    "SEUILHYD": _(u"seuil hydrique"),
    "SEUILISO": _(u"seuil isotrope"),
    "SEUIL": _(u"seuil"),
    "SHIFT_T1": _(u"glissement tangentiel 1"),
    "SHIFT_T1": _(u"glissement tangentiel 1"),
    "SHIFT_T2": _(u"glissement tangentiel 2"),
    "SHIFT_T2": _(u"glissement tangentiel 2"),
    "SIEQ": _(u"cam_clay : contrainte équivalente"),
    "SIG1": _(u"FLUA_ENDO_PORO contraintes effective squelette solide (sans pression rgi)"),
    "SIG2": _(u"FLUA_ENDO_PORO contraintes effective squelette solide (sans pression rgi)"),
    "SIG3": _(u"FLUA_ENDO_PORO contraintes effective squelette solide (sans pression rgi)"),
    "SIG4": _(u"FLUA_ENDO_PORO contraintes effective squelette solide (sans pression rgi)"),
    "SIG5": _(u"FLUA_ENDO_PORO contraintes effective squelette solide (sans pression rgi)"),
    "SIG6": _(u"FLUA_ENDO_PORO contraintes effective squelette solide (sans pression rgi)"),
    "SIGMAPIC": _(u"contrainte de pic"),
    "SIGM_N": _(u"contrainte normale"),
    "SIGM_T1": _(u"contrainte tangentielle"),
    "SIGN_GLO": _(u"contrainte mécanique normale (sans pression de fluide)"),
    "SIGP": _(u"cam_clay : contrainte de confinement"),
    "SIGRN": _(u" Pinto-Menegotto, contrainte cycle N"),
    "SIGT": _(u"norme de la contrainte tangente"),
    "SKE1": _(u"FLUA_ENDO_PORO contraintes elastiques de l etage de Kelvin"),
    "SKE2": _(u"FLUA_ENDO_PORO contraintes elastiques de l etage de Kelvin"),
    "SKE3": _(u"FLUA_ENDO_PORO contraintes elastiques de l etage de Kelvin"),
    "SKE4": _(u"FLUA_ENDO_PORO contraintes elastiques de l etage de Kelvin"),
    "SKE5": _(u"FLUA_ENDO_PORO contraintes elastiques de l etage de Kelvin"),
    "SKE6": _(u"FLUA_ENDO_PORO contraintes elastiques de l etage de Kelvin"),
    "SM1": _(u"SIMO_MIEHE, variable interne 1"),
    "SM2": _(u"SIMO_MIEHE, variable interne 2"),
    "SM3": _(u"SIMO_MIEHE, variable interne 3"),
    "SM4": _(u"SIMO_MIEHE, variable interne 4"),
    "SM5": _(u"SIMO_MIEHE, variable interne 5"),
    "SM6": _(u"SIMO_MIEHE, variable interne 6"),
    "STIL": _(u"FLUA_ENDO_PORO sulfo aluminates pour la def"),
    "SURF": _(u"contrainte de rupture par propagation,"),
    "TAILLE_GRAIN": _(u"taille de grain de la martensite"),
    "TANGENTE": _(u"Tangente au comportement"),
    "TEMP_MARTENSITE": _(u"température de transition martensitique"),
    "TEMP_MAX": _(u"température maximum"),
    "TEMPS_TRANSITION": _(u"temps de transition pour la zircaloy"),
    "TEMP": _(u"température"),
    "TEPG": _(u"FLUA_ENDO_PORO variation de volume par fissuration rgi"),
    "TEPS": _(u"FLUA_ENDO_PORO variation de volume meca total"),
    "THXY1": _(u"Hujeux : normale entrante à la surface de charge du mécanisme père du mécanisme déviatoire du plan 3, composante 1"),
    "THXY2": _(u"Hujeux : normale entrante à la surface de charge du mécanisme père du mécanisme déviatoire du plan 3, composante 2"),
    "THXZ1": _(u"Hujeux : normale entrante à la surface de charge du mécanisme père du mécanisme déviatoire du plan 2, composante 1"),
    "THXZ2": _(u"Hujeux : normale entrante à la surface de charge du mécanisme père du mécanisme déviatoire du plan 2, composante 2"),
    "THYZ1": _(u"Hujeux : normale entrante à la surface de charge du mécanisme père du mécanisme déviatoire du plan 1, composante 1"),
    "THYZ2": _(u"Hujeux : normale entrante à la surface de charge du mécanisme père du mécanisme déviatoire du plan 1, composante 2"),
    "TXX": _(u"GDEF_LOG  contrainte T, composante XX"),
    "TXY": _(u"GDEF_LOG  contrainte T, composante XY"),
    "TXZ": _(u"GDEF_LOG  contrainte T, composante XZ"),
    "TYY": _(u"GDEF_LOG  contrainte T, composante YY"),
    "TYZ": _(u"GDEF_LOG  contrainte T, composante YZ"),
    "TZZ": _(u"GDEF_LOG  contrainte T, composante ZZ"),
    "UVISQ": _(u"Déplacement concernant la partie visqueuse"),
    "VG10": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 10"),
    "VG11": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 11"),
    "VG12": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 12"),
    "VG13": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 13"),
    "VG14": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 14"),
    "VG15": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 15"),
    "VG16": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 16"),
    "VG17": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 17"),
    "VG18": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 18"),
    "VG19": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 19"),
    "VG1": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 1"),
    "VG20": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 20"),
    "VG21": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 21"),
    "VG22": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 22"),
    "VG23": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 23"),
    "VG24": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 24"),
    "VG25": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 25"),
    "VG26": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 26"),
    "VG27": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 27"),
    "VG28": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 28"),
    "VG29": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 29"),
    "VG2": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 2"),
    "VG30": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 30"),
    "VG31": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 31"),
    "VG32": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 32"),
    "VG33": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 33"),
    "VG34": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 34"),
    "VG35": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 35"),
    "VG36": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 36"),
    "VG37": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 37"),
    "VG38": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 38"),
    "VG39": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 39"),
    "VG3": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 3"),
    "VG40": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 40"),
    "VG41": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 41"),
    "VG42": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 42"),
    "VG43": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 43"),
    "VG44": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 44"),
    "VG45": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 45"),
    "VG46": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 46"),
    "VG47": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 47"),
    "VG48": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 48"),
    "VG49": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 49"),
    "VG4": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 4"),
    "VG50": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 50"),
    "VG51": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 51"),
    "VG52": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 52"),
    "VG53": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 53"),
    "VG54": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 54"),
    "VG55": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 55"),
    "VG5": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 5"),
    "VG6": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 6"),
    "VG7": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 7"),
    "VG8": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 8"),
    "VG9": _(u"comportement BETON_GRANGER, voir R7.01.01, variable interne 9"),
    "VIDE": _(u"variable interne vide"),
    "VISCHA10": _(u"VISCOCHAB, voir R5.03.12, variable interne 10"),
    "VISCHA11": _(u"VISCOCHAB, voir R5.03.12, variable interne 11"),
    "VISCHA12": _(u"VISCOCHAB, voir R5.03.12, variable interne 12"),
    "VISCHA13": _(u"VISCOCHAB, voir R5.03.12, variable interne 13"),
    "VISCHA14": _(u"VISCOCHAB, voir R5.03.12, variable interne 14"),
    "VISCHA15": _(u"VISCOCHAB, voir R5.03.12, variable interne 15"),
    "VISCHA16": _(u"VISCOCHAB, voir R5.03.12, variable interne 16"),
    "VISCHA17": _(u"VISCOCHAB, voir R5.03.12, variable interne 17"),
    "VISCHA18": _(u"VISCOCHAB, voir R5.03.12, variable interne 18"),
    "VISCHA19": _(u"VISCOCHAB, voir R5.03.12, variable interne 19"),
    "VISCHA1": _(u"VISCOCHAB, voir R5.03.12, variable interne 1"),
    "VISCHA20": _(u"VISCOCHAB, voir R5.03.12, variable interne 20"),
    "VISCHA21": _(u"VISCOCHAB, voir R5.03.12, variable interne 21"),
    "VISCHA22": _(u"VISCOCHAB, voir R5.03.12, variable interne 22"),
    "VISCHA23": _(u"VISCOCHAB, voir R5.03.12, variable interne 23"),
    "VISCHA24": _(u"VISCOCHAB, voir R5.03.12, variable interne 24"),
    "VISCHA25": _(u"VISCOCHAB, voir R5.03.12, variable interne 25"),
    "VISCHA26": _(u"VISCOCHAB, voir R5.03.12, variable interne 26"),
    "VISCHA27": _(u"VISCOCHAB, voir R5.03.12, variable interne 27"),
    "VISCHA28": _(u"VISCOCHAB, voir R5.03.12, variable interne 28"),
    "VISCHA2": _(u"VISCOCHAB, voir R5.03.12, variable interne 2"),
    "VISCHA3": _(u"VISCOCHAB, voir R5.03.12, variable interne 3"),
    "VISCHA4": _(u"VISCOCHAB, voir R5.03.12, variable interne 4"),
    "VISCHA5": _(u"VISCOCHAB, voir R5.03.12, variable interne 5"),
    "VISCHA6": _(u"VISCOCHAB, voir R5.03.12, variable interne 6"),
    "VISCHA7": _(u"VISCOCHAB, voir R5.03.12, variable interne 7"),
    "VISCHA8": _(u"VISCOCHAB, voir R5.03.12, variable interne 8"),
    "VISCHA9": _(u"VISCOCHAB, voir R5.03.12, variable interne 9"),
    "VSHR": _(u"FLUA_ENDO_PORO vide pour l eau  capillaire (necessaire sous iteration fluage3d"),
    "WELA": _(u"FLUA_ENDO_PORO  energie elastique"),    
    "WID1": _(u"FLUA_ENDO_PORO ouvertures fissures tenseur symétrique"),
    "WID2": _(u"FLUA_ENDO_PORO ouvertures fissures tenseur symétrique"),
    "WID3": _(u"FLUA_ENDO_PORO ouvertures fissures tenseur symétrique"),
    "WID4": _(u"FLUA_ENDO_PORO ouvertures fissures tenseur symétrique"),
    "WID5": _(u"FLUA_ENDO_PORO ouvertures fissures tenseur symétrique"),
    "WID6": _(u"FLUA_ENDO_PORO ouvertures fissures tenseur symétrique"),
    "WL1": _(u"FLUA_ENDO_PORO partie plastique de l ouverture de fissure localisee"),
    "WL2": _(u"FLUA_ENDO_PORO partie plastique de l ouverture de fissure localisee"),
    "WL2": _(u"ouvertures suivant les axes principaux de l'endommagement de traction localisé"),
    "WL3": _(u"FLUA_ENDO_PORO partie plastique de l ouverture de fissure localisee"),
    "WL3": _(u"ouvertures suivant les axes principaux de l'endommagement de traction localisé"),
    "WSHR": _(u"FLUA_ENDO_PORO volume d eau capillaire (necessaire sous iteration fluage3d)"),    "WL1": _(u"ouvertures suivant les axes principaux de l'endommagement de traction localisé"),
    "X1": _(u"coordonnée X de la pointe de fissure après rupture par propagation,"),
    "X2": _(u"coordonnée X de la pointe de fissure 2 lors de l'amorçage,"),
    "XCINXX": _(u"tenseur cinématique, composante XX"),
    "XCINXY": _(u"tenseur cinématique, composante XY"),
    "XCINXZ": _(u"tenseur cinématique, composante XZ"),
    "XCINYY": _(u"tenseur cinématique, composante YY"),
    "XCINYZ": _(u"tenseur cinématique, composante YZ"),
    "XCINZZ": _(u"tenseur cinématique, composante ZZ"),
    "XFLEX1": _(u"GLRC_DAMAGE : tenseur d'écrouissage cinématique en flexion composante 1"),
    "XFLEX2": _(u"GLRC_DAMAGE : tenseur d'écrouissage cinématique en flexion composante 2"),
    "XFLEX3": _(u"GLRC_DAMAGE : tenseur d'écrouissage cinématique en flexion composante 3"),
    "XHXY1": _(u"Hujeux : coordonnée du point de tangence à la surface de charge du mécanisme déviatoire du plan 3, composante 1"),
    "XHXY2": _(u"Hujeux : coordonnée du point de tangence à la surface de charge du mécanisme déviatoire du plan 3, composante 2"),
    "XHXZ1": _(u"Hujeux : coordonnée du point de tangence à la surface de charge du mécanisme déviatoire du plan 2, composante1"),
    "XHXZ2": _(u"Hujeux : coordonnée du point de tangence à la surface de charge du mécanisme déviatoire du plan 2, composante2"),
    "XHYZ1": _(u"Hujeux : coordonnée du point de tangence à la surface de charge du mécanisme déviatoire du plan 1, composante 1"),
    "XHYZ2": _(u"Hujeux : coordonnée du point de tangence à la surface de charge du mécanisme déviatoire du plan 1, composante 2"),
    "XIP": _(u"variable d'écrouissage élastoplastique"),
    "XIVP": _(u"variable d'écrouissage viscoplastique"),
    "XMEMB1": _(u"GLRC_DAMAGE : tenseur d'écrouissage cinématique en membrane composante 1"),
    "XMEMB2": _(u"GLRC_DAMAGE : tenseur d'écrouissage cinématique en membrane composante 2"),
    "XMEMB3": _(u"GLRC_DAMAGE : tenseur d'écrouissage cinématique en membrane composante 3"),
    "Y1": _(u"coordonnée Y de la pointe de fissure après rupture par propagation,"),
    "Y2": _(u"coordonnée Y de la pointe de fissure 2 lors de l'amorçage,"),
    "ZIRCALBE": _(u"phase métallurgique zirconium ALPHA/BETA"),
    "ZIRCALPH": _(u"phase métallurgique zirconium ALPHA"),
    "ZIRCBETA": _(u"phase métallurgique zirconium BETA"),
}
