/* -------------------------------------------------------------------- */
/* Copyright (C) 1991 - 2020 - EDF R&D - www.code-aster.org             */
/* This file is part of code_aster.                                     */
/*                                                                      */
/* code_aster is free software: you can redistribute it and/or modify   */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation, either version 3 of the License, or    */
/* (at your option) any later version.                                  */
/*                                                                      */
/* code_aster is distributed in the hope that it will be useful,        */
/* but WITHOUT ANY WARRANTY; without even the implied warranty of       */
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        */
/* GNU General Public License for more details.                         */
/*                                                                      */
/* You should have received a copy of the GNU General Public License    */
/* along with code_aster.  If not, see <http://www.gnu.org/licenses/>.  */
/* -------------------------------------------------------------------- */

/* disable the message "line too long" because the code is generated  */
/* aslint: disable=C3001 */

#ifndef DEFINITION_H
#define DEFINITION_H

#include "aster_depend.h"

/* Pour définir les appels et signatures de fonctions appelables en Fortran
 * On utilise l'operateur de concatenation ## du préprocesseur C (cpp) pour ajouter l'underscore
 * au nom en majuscule ou minuscule de la fonction à définir ou à appeler.
 * Pour les anciens compilateurs non ANSI, utiliser un commentaire vide à la place.
 * Pour appeler une subroutine Fortran de nom SUB avec un argument string et 2 arguments autres, faire:
 * #define CALL_SUB(a,b,c) CALLSPP(SUB,sub,a,b,c)
 * puis : CALL_SUB(a,b,c)
 * Pour définir une fonction C de nom SUB avec un argument string et 2 arguments autres,
 * appelable depuis le fortran, faire:
 * void DEFSPP(SUB, sub, char * nomobj, STRING_SIZE lnom, ASTERDOUBLE *d, ASTERINTEGER *i)
 * {
 * }
 * ici, lnom est l'entier qui indique la longueur de la chaine Fortran nomobj
 * Les macros définies ici ne servent qu'à former le nom de la fonction et à
 * mettre les arguments dans le bon ordre. On utilise l'ordre _WIN32 comme
 * base (pointeur char suivi de la longueur) et on reordonne pour les autres compilateurs.
 * STRING_SIZE est le type retourné par strlen.
 */

/*
 * V is used for a value <type string> returned by a function.
 * The first two arguments are for the return of the function.
 */

/*
 * O is used for a C++ <std::string> object (only for CALLxx).
 * One uses '.char_ptr()' for the pointeur and '.size()' instead of 'strlen'.
 */

/* Operateur de concatenation */
#define  _(A,B)   A##B

/* Appels : minuscules/majuscules, avec/sans underscore */
#if defined _POSIX
#   define F_FUNC(UN,LN)           _(LN,_)
#   if defined _NO_UNDERSCORE
#       define F_FUNC(UN,LN)           LN
#   endif
#else
#   define F_FUNC(UN,LN)           UN
#endif

/* http://gcc.gnu.org/onlinedocs/cpp/Stringification.html */
#define xstr(s)                 str(s)
/* not with c++ */
#ifndef __cplusplus
#   define str(s)               #s
#endif

#define S_FUNC(UN,LN)           xstr(F_FUNC(UN,LN))

/* STDCALL for "old" windows version */
#ifdef _USE_STDCALL
#   define STDCALL(UN,LN)   __stdcall F_FUNC(UN,LN)
#else
#   define STDCALL(UN,LN)   F_FUNC(UN,LN)
#endif

/* Appels et signatures avec strlen en fin de liste */
#ifdef _STRLEN_AT_END

#define DEFS(UN,LN,a,la)               STDCALL(UN,LN)(a,la)
#define CALLS(UN,LN,a)                 F_FUNC(UN,LN)(a,strlen(a))
#define CALLO(UN,LN,a)                 F_FUNC(UN,LN)((a).c_str(),(a).size())
#define DEFPS(UN,LN,a,b,lb)               STDCALL(UN,LN)(a,b,lb)
#define CALLPS(UN,LN,a,b)                 F_FUNC(UN,LN)(a,b,strlen(b))
#define CALLPO(UN,LN,a,b)                 F_FUNC(UN,LN)(a,(b).c_str(),(b).size())
#define DEFSP(UN,LN,a,la,b)               STDCALL(UN,LN)(a,b,la)
#define CALLSP(UN,LN,a,b)                 F_FUNC(UN,LN)(a,b,strlen(a))
#define CALLOP(UN,LN,a,b)                 F_FUNC(UN,LN)((a).c_str(),b,(a).size())
#define DEFSS(UN,LN,a,la,b,lb)               STDCALL(UN,LN)(a,b,la,lb)
#define CALLSS(UN,LN,a,b)                    F_FUNC(UN,LN)(a,b,strlen(a),strlen(b))
#define CALLOO(UN,LN,a,b)                    F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(a).size(),(b).size())
#define DEFPSS(UN,LN,a,b,lb,c,lc)               STDCALL(UN,LN)(a,b,c,lb,lc)
#define CALLPSS(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,b,c,strlen(b),strlen(c))
#define CALLPOO(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,(b).c_str(),(c).c_str(),(b).size(),(c).size())
#define DEFSPP(UN,LN,a,la,b,c)               STDCALL(UN,LN)(a,b,c,la)
#define CALLSPP(UN,LN,a,b,c)                 F_FUNC(UN,LN)(a,b,c,strlen(a))
#define CALLOPP(UN,LN,a,b,c)                 F_FUNC(UN,LN)((a).c_str(),b,c,(a).size())
#define DEFSPS(UN,LN,a,la,b,c,lc)               STDCALL(UN,LN)(a,b,c,la,lc)
#define CALLSPS(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,b,c,strlen(a),strlen(c))
#define CALLOPO(UN,LN,a,b,c)                    F_FUNC(UN,LN)((a).c_str(),b,(c).c_str(),(a).size(),(c).size())
#define DEFSSP(UN,LN,a,la,b,lb,c)               STDCALL(UN,LN)(a,b,c,la,lb)
#define CALLSSP(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,b,c,strlen(a),strlen(b))
#define CALLOOP(UN,LN,a,b,c)                    F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,(a).size(),(b).size())
#define DEFSSS(UN,LN,a,la,b,lb,c,lc)               STDCALL(UN,LN)(a,b,c,la,lb,lc)
#define CALLSSS(UN,LN,a,b,c)                       F_FUNC(UN,LN)(a,b,c,strlen(a),strlen(b),strlen(c))
#define CALLOOO(UN,LN,a,b,c)                       F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(a).size(),(b).size(),(c).size())
#define DEFVSP(UN,LN,a,la,b,lb,c)               STDCALL(UN,LN)(a,la,b,c,lb)
#define CALLVSP(UN,LN,a,b,c)                 F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(b))
#define CALLVOP(UN,LN,a,b,c)                 F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),c,(b).size())
#define DEFVSS(UN,LN,a,la,b,lb,c,lc)               STDCALL(UN,LN)(a,la,b,c,lb,lc)
#define CALLVSS(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(b),strlen(c))
#define CALLVOO(UN,LN,a,b,c)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(c).c_str(),(b).size(),(c).size())
#define DEFPPSP(UN,LN,a,b,c,lc,d)               STDCALL(UN,LN)(a,b,c,d,lc)
#define CALLPPSP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,b,c,d,strlen(c))
#define CALLPPOP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,b,(c).c_str(),d,(c).size())
#define DEFPSPP(UN,LN,a,b,lb,c,d)               STDCALL(UN,LN)(a,b,c,d,lb)
#define CALLPSPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,b,c,d,strlen(b))
#define CALLPOPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,(b).c_str(),c,d,(b).size())
#define DEFPSPS(UN,LN,a,b,lb,c,d,ld)               STDCALL(UN,LN)(a,b,c,d,lb,ld)
#define CALLPSPS(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,b,c,d,strlen(b),strlen(d))
#define CALLPOPO(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,(b).c_str(),c,(d).c_str(),(b).size(),(d).size())
#define DEFSPPP(UN,LN,a,la,b,c,d)               STDCALL(UN,LN)(a,b,c,d,la)
#define CALLSPPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,b,c,d,strlen(a))
#define CALLOPPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)((a).c_str(),b,c,d,(a).size())
#define DEFSPPS(UN,LN,a,la,b,c,d,ld)               STDCALL(UN,LN)(a,b,c,d,la,ld)
#define CALLSPPS(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,b,c,d,strlen(a),strlen(d))
#define CALLOPPO(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)((a).c_str(),b,c,(d).c_str(),(a).size(),(d).size())
#define DEFSPSP(UN,LN,a,la,b,c,lc,d)               STDCALL(UN,LN)(a,b,c,d,la,lc)
#define CALLSPSP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,b,c,d,strlen(a),strlen(c))
#define CALLOPOP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)((a).c_str(),b,(c).c_str(),d,(a).size(),(c).size())
#define DEFSPSS(UN,LN,a,la,b,c,lc,d,ld)               STDCALL(UN,LN)(a,b,c,d,la,lc,ld)
#define CALLSPSS(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)(a,b,c,d,strlen(a),strlen(c),strlen(d))
#define CALLOPOO(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)((a).c_str(),b,(c).c_str(),(d).c_str(),(a).size(),(c).size(),(d).size())
#define DEFSSPP(UN,LN,a,la,b,lb,c,d)               STDCALL(UN,LN)(a,b,c,d,la,lb)
#define CALLSSPP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,b,c,d,strlen(a),strlen(b))
#define CALLOOPP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,d,(a).size(),(b).size())
#define DEFSSPS(UN,LN,a,la,b,lb,c,d,ld)               STDCALL(UN,LN)(a,b,c,d,la,lb,ld)
#define CALLSSPS(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)(a,b,c,d,strlen(a),strlen(b),strlen(d))
#define CALLOOPO(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,(d).c_str(),(a).size(),(b).size(),(d).size())
#define DEFSSSP(UN,LN,a,la,b,lb,c,lc,d)               STDCALL(UN,LN)(a,b,c,d,la,lb,lc)
#define CALLSSSP(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)(a,b,c,d,strlen(a),strlen(b),strlen(c))
#define CALLOOOP(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),d,(a).size(),(b).size(),(c).size())
#define DEFSSSS(UN,LN,a,la,b,lb,c,lc,d,ld)               STDCALL(UN,LN)(a,b,c,d,la,lb,lc,ld)
#define CALLSSSS(UN,LN,a,b,c,d)                          F_FUNC(UN,LN)(a,b,c,d,strlen(a),strlen(b),strlen(c),strlen(d))
#define CALLOOOO(UN,LN,a,b,c,d)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),(a).size(),(b).size(),(c).size(),(d).size())
#define DEFPPPSP(UN,LN,a,b,c,d,ld,e)               STDCALL(UN,LN)(a,b,c,d,e,ld)
#define CALLPPPSP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)(a,b,c,d,e,strlen(d))
#define CALLPPPOP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)(a,b,c,(d).c_str(),e,(d).size())
#define DEFPSSSS(UN,LN,a,b,lb,c,lc,d,ld,e,le)               STDCALL(UN,LN)(a,b,c,d,e,lb,lc,ld,le)
#define CALLPSSSS(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,b,c,d,e,strlen(b),strlen(c),strlen(d),strlen(e))
#define CALLPOOOO(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,(b).c_str(),(c).c_str(),(d).c_str(),(e).c_str(),(b).size(),(c).size(),(d).size(),(e).size())
#define DEFSPPPP(UN,LN,a,la,b,c,d,e)               STDCALL(UN,LN)(a,b,c,d,e,la)
#define CALLSPPPP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)(a,b,c,d,e,strlen(a))
#define CALLOPPPP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)((a).c_str(),b,c,d,e,(a).size())
#define DEFSSPPP(UN,LN,a,la,b,lb,c,d,e)               STDCALL(UN,LN)(a,b,c,d,e,la,lb)
#define CALLSSPPP(UN,LN,a,b,c,d,e)                    F_FUNC(UN,LN)(a,b,c,d,e,strlen(a),strlen(b))
#define CALLOOPPP(UN,LN,a,b,c,d,e)                    F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,d,e,(a).size(),(b).size())
#define DEFSSPSS(UN,LN,a,la,b,lb,c,d,ld,e,le)               STDCALL(UN,LN)(a,b,c,d,e,la,lb,ld,le)
#define CALLSSPSS(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,b,c,d,e,strlen(a),strlen(b),strlen(d),strlen(e))
#define CALLOOPOO(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,(d).c_str(),(e).c_str(),(a).size(),(b).size(),(d).size(),(e).size())
#define DEFSSSPP(UN,LN,a,la,b,lb,c,lc,d,e)               STDCALL(UN,LN)(a,b,c,d,e,la,lb,lc)
#define CALLSSSPP(UN,LN,a,b,c,d,e)                       F_FUNC(UN,LN)(a,b,c,d,e,strlen(a),strlen(b),strlen(c))
#define CALLOOOPP(UN,LN,a,b,c,d,e)                       F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),d,e,(a).size(),(b).size(),(c).size())
#define DEFSSSSP(UN,LN,a,la,b,lb,c,lc,d,ld,e)               STDCALL(UN,LN)(a,b,c,d,e,la,lb,lc,ld)
#define CALLSSSSP(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,b,c,d,e,strlen(a),strlen(b),strlen(c),strlen(d))
#define CALLOOOOP(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),e,(a).size(),(b).size(),(c).size(),(d).size())
#define DEFSSSSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,le)               STDCALL(UN,LN)(a,b,c,d,e,la,lb,lc,ld,le)
#define CALLSSSSS(UN,LN,a,b,c,d,e)                             F_FUNC(UN,LN)(a,b,c,d,e,strlen(a),strlen(b),strlen(c),strlen(d),strlen(e))
#define CALLOOOOO(UN,LN,a,b,c,d,e)                             F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),(e).c_str(),(a).size(),(b).size(),(c).size(),(d).size(),(e).size())
#define DEFSPPSSP(UN,LN,a,la,b,c,d,ld,e,le,f)               STDCALL(UN,LN)(a,b,c,d,e,f,la,ld,le)
#define CALLSPPSSP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(d),strlen(e))
#define CALLOPPOOP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)((a).c_str(),b,c,(d).c_str(),(e).c_str(),f,(a).size(),(d).size(),(e).size())
#define DEFSSPPPP(UN,LN,a,la,b,lb,c,d,e,f)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb)
#define CALLSSPPPP(UN,LN,a,b,c,d,e,f)                    F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b))
#define CALLOOPPPP(UN,LN,a,b,c,d,e,f)                    F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,d,e,f,(a).size(),(b).size())
#define DEFSSPPSP(UN,LN,a,la,b,lb,c,d,e,le,f)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb,le)
#define CALLSSPPSP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b),strlen(e))
#define CALLOOPPOP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,d,(e).c_str(),f,(a).size(),(b).size(),(e).size())
#define DEFSSPPSS(UN,LN,a,la,b,lb,c,d,e,le,f,lf)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb,le,lf)
#define CALLSSPPSS(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b),strlen(e),strlen(f))
#define CALLOOPPOO(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,d,(e).c_str(),(f).c_str(),(a).size(),(b).size(),(e).size(),(f).size())
#define DEFSSSPSP(UN,LN,a,la,b,lb,c,lc,d,e,le,f)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb,lc,le)
#define CALLSSSPSP(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b),strlen(c),strlen(e))
#define CALLOOOPOP(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),d,(e).c_str(),f,(a).size(),(b).size(),(c).size(),(e).size())
#define DEFSSSPSS(UN,LN,a,la,b,lb,c,lc,d,e,le,f,lf)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb,lc,le,lf)
#define CALLSSSPSS(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b),strlen(c),strlen(e),strlen(f))
#define CALLOOOPOO(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),d,(e).c_str(),(f).c_str(),(a).size(),(b).size(),(c).size(),(e).size(),(f).size())
#define DEFSSSSPS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb,lc,ld,lf)
#define CALLSSSSPS(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b),strlen(c),strlen(d),strlen(f))
#define CALLOOOOPO(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),e,(f).c_str(),(a).size(),(b).size(),(c).size(),(d).size(),(f).size())
#define DEFSSSSSP(UN,LN,a,la,b,lb,c,lc,d,ld,e,le,f)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb,lc,ld,le)
#define CALLSSSSSP(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b),strlen(c),strlen(d),strlen(e))
#define CALLOOOOOP(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),(e).c_str(),f,(a).size(),(b).size(),(c).size(),(d).size(),(e).size())
#define DEFSSSSSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,le,f,lf)               STDCALL(UN,LN)(a,b,c,d,e,f,la,lb,lc,ld,le,lf)
#define CALLSSSSSS(UN,LN,a,b,c,d,e,f)                                F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(a),strlen(b),strlen(c),strlen(d),strlen(e),strlen(f))
#define CALLOOOOOO(UN,LN,a,b,c,d,e,f)                                F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),(e).c_str(),(f).c_str(),(a).size(),(b).size(),(c).size(),(d).size(),(e).size(),(f).size())
#define DEFPSSSPSP(UN,LN,a,b,lb,c,lc,d,ld,e,f,lf,g)               STDCALL(UN,LN)(a,b,c,d,e,f,g,lb,lc,ld,lf)
#define CALLPSSSPSP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(b),strlen(c),strlen(d),strlen(f))
#define CALLPOOOPOP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,(b).c_str(),(c).c_str(),(d).c_str(),e,(f).c_str(),g,(b).size(),(c).size(),(d).size(),(f).size())
#define DEFSPPPPPP(UN,LN,a,la,b,c,d,e,f,g)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la)
#define CALLSPPPPPP(UN,LN,a,b,c,d,e,f,g)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a))
#define CALLOPPPPPP(UN,LN,a,b,c,d,e,f,g)                 F_FUNC(UN,LN)((a).c_str(),b,c,d,e,f,g,(a).size())
#define DEFSPPSSSP(UN,LN,a,la,b,c,d,ld,e,le,f,lf,g)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la,ld,le,lf)
#define CALLSPPSSSP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a),strlen(d),strlen(e),strlen(f))
#define CALLOPPOOOP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)((a).c_str(),b,c,(d).c_str(),(e).c_str(),(f).c_str(),g,(a).size(),(d).size(),(e).size(),(f).size())
#define DEFSPSPPPS(UN,LN,a,la,b,c,lc,d,e,f,g,lg)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la,lc,lg)
#define CALLSPSPPPS(UN,LN,a,b,c,d,e,f,g)                       F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a),strlen(c),strlen(g))
#define CALLOPOPPPO(UN,LN,a,b,c,d,e,f,g)                       F_FUNC(UN,LN)((a).c_str(),b,(c).c_str(),d,e,f,(g).c_str(),(a).size(),(c).size(),(g).size())
#define DEFSSPPPPP(UN,LN,a,la,b,lb,c,d,e,f,g)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la,lb)
#define CALLSSPPPPP(UN,LN,a,b,c,d,e,f,g)                    F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a),strlen(b))
#define CALLOOPPPPP(UN,LN,a,b,c,d,e,f,g)                    F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,d,e,f,g,(a).size(),(b).size())
#define DEFSSPSSPP(UN,LN,a,la,b,lb,c,d,ld,e,le,f,g)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la,lb,ld,le)
#define CALLSSPSSPP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a),strlen(b),strlen(d),strlen(e))
#define CALLOOPOOPP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,(d).c_str(),(e).c_str(),f,g,(a).size(),(b).size(),(d).size(),(e).size())
#define DEFSSSPSSP(UN,LN,a,la,b,lb,c,lc,d,e,le,f,lf,g)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la,lb,lc,le,lf)
#define CALLSSSPSSP(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a),strlen(b),strlen(c),strlen(e),strlen(f))
#define CALLOOOPOOP(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),d,(e).c_str(),(f).c_str(),g,(a).size(),(b).size(),(c).size(),(e).size(),(f).size())
#define DEFSSSSPPS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,g,lg)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la,lb,lc,ld,lg)
#define CALLSSSSPPS(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a),strlen(b),strlen(c),strlen(d),strlen(g))
#define CALLOOOOPPO(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),e,f,(g).c_str(),(a).size(),(b).size(),(c).size(),(d).size(),(g).size())
#define DEFSSSSPSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg)               STDCALL(UN,LN)(a,b,c,d,e,f,g,la,lb,lc,ld,lf,lg)
#define CALLSSSSPSS(UN,LN,a,b,c,d,e,f,g)                                F_FUNC(UN,LN)(a,b,c,d,e,f,g,strlen(a),strlen(b),strlen(c),strlen(d),strlen(f),strlen(g))
#define CALLOOOOPOO(UN,LN,a,b,c,d,e,f,g)                                F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),e,(f).c_str(),(g).c_str(),(a).size(),(b).size(),(c).size(),(d).size(),(f).size(),(g).size())
#define DEFPPPPSPPP(UN,LN,a,b,c,d,e,le,f,g,h)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,le)
#define CALLPPPPSPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,strlen(e))
#define CALLPPPPOPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,c,d,(e).c_str(),f,g,h,(e).size())
#define DEFPPPPSPSP(UN,LN,a,b,c,d,e,le,f,g,lg,h)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,le,lg)
#define CALLPPPPSPSP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,strlen(e),strlen(g))
#define CALLPPPPOPOP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,b,c,d,(e).c_str(),f,(g).c_str(),h,(e).size(),(g).size())
#define DEFPPPPSPSS(UN,LN,a,b,c,d,e,le,f,g,lg,h,lh)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,le,lg,lh)
#define CALLPPPPSPSS(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,strlen(e),strlen(g),strlen(h))
#define CALLPPPPOPOO(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)(a,b,c,d,(e).c_str(),f,(g).c_str(),(h).c_str(),(e).size(),(g).size(),(h).size())
#define DEFPPSPPPPP(UN,LN,a,b,c,lc,d,e,f,g,h)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,lc)
#define CALLPPSPPPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,strlen(c))
#define CALLPPOPPPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,(c).c_str(),d,e,f,g,h,(c).size())
#define DEFPSPSPPPP(UN,LN,a,b,lb,c,d,ld,e,f,g,h)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,lb,ld)
#define CALLPSPSPPPP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,strlen(b),strlen(d))
#define CALLPOPOPPPP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,(b).c_str(),c,(d).c_str(),e,f,g,h,(b).size(),(d).size())
#define DEFSPPPPPPS(UN,LN,a,la,b,c,d,e,f,g,h,lh)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,la,lh)
#define CALLSPPPPPPS(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,strlen(a),strlen(h))
#define CALLOPPPPPPO(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)((a).c_str(),b,c,d,e,f,g,(h).c_str(),(a).size(),(h).size())
#define DEFSSSPPPPP(UN,LN,a,la,b,lb,c,lc,d,e,f,g,h)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,la,lb,lc)
#define CALLSSSPPPPP(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,strlen(a),strlen(b),strlen(c))
#define CALLOOOPPPPP(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),d,e,f,g,h,(a).size(),(b).size(),(c).size())
#define DEFPSSSSSSPS(UN,LN,a,b,lb,c,lc,d,ld,e,le,f,lf,g,lg,h,i,li)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,lb,lc,ld,le,lf,lg,li)
#define CALLPSSSSSSPS(UN,LN,a,b,c,d,e,f,g,h,i)                                   F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,strlen(b),strlen(c),strlen(d),strlen(e),strlen(f),strlen(g),strlen(i))
#define CALLPOOOOOOPO(UN,LN,a,b,c,d,e,f,g,h,i)                                   F_FUNC(UN,LN)(a,(b).c_str(),(c).c_str(),(d).c_str(),(e).c_str(),(f).c_str(),(g).c_str(),h,(i).c_str(),(b).size(),(c).size(),(d).size(),(e).size(),(f).size(),(g).size(),(i).size())
#define DEFSPPSPPPSP(UN,LN,a,la,b,c,d,ld,e,f,g,h,lh,i)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,la,ld,lh)
#define CALLSPPSPPPSP(UN,LN,a,b,c,d,e,f,g,h,i)                       F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,strlen(a),strlen(d),strlen(h))
#define CALLOPPOPPPOP(UN,LN,a,b,c,d,e,f,g,h,i)                       F_FUNC(UN,LN)((a).c_str(),b,c,(d).c_str(),e,f,g,(h).c_str(),i,(a).size(),(d).size(),(h).size())
#define DEFSPPSSPSPS(UN,LN,a,la,b,c,d,ld,e,le,f,g,lg,h,i,li)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,la,ld,le,lg,li)
#define CALLSPPSSPSPS(UN,LN,a,b,c,d,e,f,g,h,i)                             F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,strlen(a),strlen(d),strlen(e),strlen(g),strlen(i))
#define CALLOPPOOPOPO(UN,LN,a,b,c,d,e,f,g,h,i)                             F_FUNC(UN,LN)((a).c_str(),b,c,(d).c_str(),(e).c_str(),f,(g).c_str(),h,(i).c_str(),(a).size(),(d).size(),(e).size(),(g).size(),(i).size())
#define DEFSSSSPSSSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg,h,lh,i,li)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,la,lb,lc,ld,lf,lg,lh,li)
#define CALLSSSSPSSSS(UN,LN,a,b,c,d,e,f,g,h,i)                                      F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,strlen(a),strlen(b),strlen(c),strlen(d),strlen(f),strlen(g),strlen(h),strlen(i))
#define CALLOOOOPOOOO(UN,LN,a,b,c,d,e,f,g,h,i)                                      F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),e,(f).c_str(),(g).c_str(),(h).c_str(),(i).c_str(),(a).size(),(b).size(),(c).size(),(d).size(),(f).size(),(g).size(),(h).size(),(i).size())
#define DEFPPPPPSPPPP(UN,LN,a,b,c,d,e,f,lf,g,h,i,j)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,lf)
#define CALLPPPPPSPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,strlen(f))
#define CALLPPPPPOPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                 F_FUNC(UN,LN)(a,b,c,d,e,(f).c_str(),g,h,i,j,(f).size())
#define DEFPPPPPSPPSP(UN,LN,a,b,c,d,e,f,lf,g,h,i,li,j)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,lf,li)
#define CALLPPPPPSPPSP(UN,LN,a,b,c,d,e,f,g,h,i,j)                    F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,strlen(f),strlen(i))
#define CALLPPPPPOPPOP(UN,LN,a,b,c,d,e,f,g,h,i,j)                    F_FUNC(UN,LN)(a,b,c,d,e,(f).c_str(),g,h,(i).c_str(),j,(f).size(),(i).size())
#define DEFSPSPSPPPPS(UN,LN,a,la,b,c,lc,d,e,le,f,g,h,i,j,lj)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,la,lc,le,lj)
#define CALLSPSPSPPPPS(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,strlen(a),strlen(c),strlen(e),strlen(j))
#define CALLOPOPOPPPPO(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)((a).c_str(),b,(c).c_str(),d,(e).c_str(),f,g,h,i,(j).c_str(),(a).size(),(c).size(),(e).size(),(j).size())
#define DEFSPSSSPSSPS(UN,LN,a,la,b,c,lc,d,ld,e,le,f,g,lg,h,lh,i,j,lj)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,la,lc,ld,le,lg,lh,lj)
#define DEFSPSSSSPSSPS(UN,LN,a,la,b,c,lc,d,ld,e,le,f,lf,g,h,lh,i,li,j,k,lk)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,la,lc,ld,le,lf,lh,li,lk)
#define CALLSPSSSPSSPS(UN,LN,a,b,c,d,e,f,g,h,i,j)                                   F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,strlen(a),strlen(c),strlen(d),strlen(e),strlen(g),strlen(h),strlen(j))
#define CALLOPOOOPOOPO(UN,LN,a,b,c,d,e,f,g,h,i,j)                                   F_FUNC(UN,LN)((a).c_str(),b,(c).c_str(),(d).c_str(),(e).c_str(),f,(g).c_str(),(h).c_str(),i,(j).c_str(),(a).size(),(c).size(),(d).size(),(e).size(),(g).size(),(h).size(),(j).size())
#define CALLOPOOOOPOOPO(UN,LN,a,b,c,d,e,f,g,h,i,j,k)                                   F_FUNC(UN,LN)((a).c_str(),b,(c).c_str(),(d).c_str(), (e).c_str() ,(f).c_str(),g,(h).c_str(),(i).c_str(),j,(k).c_str(),(a).size(),(c).size(),(d).size(),(e).size(),(f).size(),(h).size(),(i).size(),(k).size())
#define DEFSSPSPPPPPS(UN,LN,a,la,b,lb,c,d,ld,e,f,g,h,i,j,lj)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,la,lb,ld,lj)
#define CALLSSPSPPPPPS(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,strlen(a),strlen(b),strlen(d),strlen(j))
#define CALLOOPOPPPPPO(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,(d).c_str(),e,f,g,h,i,(j).c_str(),(a).size(),(b).size(),(d).size(),(j).size())
#define DEFSSPSPPSPPP(UN,LN,a,la,b,lb,c,d,ld,e,f,g,lg,h,i,j)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,la,lb,ld,lg)
#define CALLSSPSPPSPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,strlen(a),strlen(b),strlen(d),strlen(g))
#define CALLOOPOPPOPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,(d).c_str(),e,f,(g).c_str(),h,i,j,(a).size(),(b).size(),(d).size(),(g).size())
#define DEFSSSSSSSPPPP(UN,LN,a,la,b,lb,c,lc,d,ld,e,le,f,lf,g,lg,h,i,j,k)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,la,lb,lc,ld,le,lf,lg)
#define CALLSSSSSSSPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k)                                   F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,strlen(a),strlen(b),strlen(c),strlen(d),strlen(e),strlen(f),strlen(g))
#define CALLOOOOOOOPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k)                                   F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),(e).c_str(),(f).c_str(),(g).c_str(),h,i,j,k,(a).size(),(b).size(),(c).size(),(d).size(),(e).size(),(f).size(),(g).size())
#define DEFSSSSPSSSSPPP(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg,h,lh,i,li,j,k,l)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,la,lb,lc,ld,lf,lg,lh,li)
#define CALLSSSSPSSSSPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l)                                      F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,strlen(a),strlen(b),strlen(c),strlen(d),strlen(f),strlen(g),strlen(h),strlen(i))
#define CALLOOOOPOOOOPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l)                                      F_FUNC(UN,LN)((a).c_str(),(b).c_str(),(c).c_str(),(d).c_str(),e,(f).c_str(),(g).c_str(),(h).c_str(),(i).c_str(),j,k,l,(a).size(),(b).size(),(c).size(),(d).size(),(f).size(),(g).size(),(h).size(),(i).size())
#define DEFSSPPPPPPPPPPPP(UN,LN,a,la,b,lb,c,d,e,f,g,h,i,j,k,l,m,n)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,la,lb)
#define CALLSSPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n)                    F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,strlen(a),strlen(b))
#define CALLOOPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n)                    F_FUNC(UN,LN)((a).c_str(),(b).c_str(),c,d,e,f,g,h,i,j,k,l,m,n,(a).size(),(b).size())
#define DEFPPPPPPPPPPPPPPPPPPPSPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,lt,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,lt)
#define CALLPPPPPPPPPPPPPPPPPPPSPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,strlen(t))
#define CALLPPPPPPPPPPPPPPPPPPPOPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,(t).c_str(),u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,(t).size())

/* Appels et signatures avec strlen juste après le pointeur de chaine */
#else

#define DEFS(UN,LN,a,la)               STDCALL(UN,LN)(a,la)
#define CALLS(UN,LN,a)                 F_FUNC(UN,LN)(a,strlen(a))
#define CALLO(UN,LN,a)                 F_FUNC(UN,LN)((a).c_str(),(a).size())
#define DEFPS(UN,LN,a,b,lb)               STDCALL(UN,LN)(a,b,lb)
#define CALLPS(UN,LN,a,b)                 F_FUNC(UN,LN)(a,b,strlen(b))
#define CALLPO(UN,LN,a,b)                 F_FUNC(UN,LN)(a,(b).c_str(),(b).size())
#define DEFSP(UN,LN,a,la,b)               STDCALL(UN,LN)(a,la,b)
#define CALLSP(UN,LN,a,b)                 F_FUNC(UN,LN)(a,strlen(a),b)
#define CALLOP(UN,LN,a,b)                 F_FUNC(UN,LN)((a).c_str(),(a).size(),b)
#define DEFSS(UN,LN,a,la,b,lb)               STDCALL(UN,LN)(a,la,b,lb)
#define CALLSS(UN,LN,a,b)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b))
#define CALLOO(UN,LN,a,b)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size())
#define DEFPSS(UN,LN,a,b,lb,c,lc)               STDCALL(UN,LN)(a,b,lb,c,lc)
#define CALLPSS(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,b,strlen(b),c,strlen(c))
#define CALLPOO(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,(b).c_str(),(b).size(),(c).c_str(),(c).size())
#define DEFSPP(UN,LN,a,la,b,c)               STDCALL(UN,LN)(a,la,b,c)
#define CALLSPP(UN,LN,a,b,c)                 F_FUNC(UN,LN)(a,strlen(a),b,c)
#define CALLOPP(UN,LN,a,b,c)                 F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c)
#define DEFSPS(UN,LN,a,la,b,c,lc)               STDCALL(UN,LN)(a,la,b,c,lc)
#define CALLSPS(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(c))
#define CALLOPO(UN,LN,a,b,c)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),b,(c).c_str(),(c).size())
#define DEFSSP(UN,LN,a,la,b,lb,c)               STDCALL(UN,LN)(a,la,b,lb,c)
#define CALLSSP(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c)
#define CALLOOP(UN,LN,a,b,c)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c)
#define DEFSSS(UN,LN,a,la,b,lb,c,lc)               STDCALL(UN,LN)(a,la,b,lb,c,lc)
#define CALLSSS(UN,LN,a,b,c)                       F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c))
#define CALLOOO(UN,LN,a,b,c)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size())
#define DEFVSP(UN,LN,a,la,b,lb,c)               STDCALL(UN,LN)(a,la,b,lb,c)
#define CALLVSP(UN,LN,a,b,c)                 F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c)
#define CALLVOP(UN,LN,a,b,c)                 F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c)
#define DEFVSS(UN,LN,a,la,b,lb,c,lc)               STDCALL(UN,LN)(a,la,b,lb,c,lc)
#define CALLVSS(UN,LN,a,b,c)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c))
#define CALLVOO(UN,LN,a,b,c)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size())
#define DEFPPSP(UN,LN,a,b,c,lc,d)               STDCALL(UN,LN)(a,b,c,lc,d)
#define CALLPPSP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,b,c,strlen(c),d)
#define CALLPPOP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,b,(c).c_str(),(c).size(),d)
#define DEFPSPP(UN,LN,a,b,lb,c,d)               STDCALL(UN,LN)(a,b,lb,c,d)
#define CALLPSPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,b,strlen(b),c,d)
#define CALLPOPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,(b).c_str(),(b).size(),c,d)
#define DEFPSPS(UN,LN,a,b,lb,c,d,ld)               STDCALL(UN,LN)(a,b,lb,c,d,ld)
#define CALLPSPS(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,b,strlen(b),c,d,strlen(d))
#define CALLPOPO(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,(b).c_str(),(b).size(),c,(d).c_str(),(d).size())
#define DEFSPPP(UN,LN,a,la,b,c,d)               STDCALL(UN,LN)(a,la,b,c,d)
#define CALLSPPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)(a,strlen(a),b,c,d)
#define CALLOPPP(UN,LN,a,b,c,d)                 F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,d)
#define DEFSPPS(UN,LN,a,la,b,c,d,ld)               STDCALL(UN,LN)(a,la,b,c,d,ld)
#define CALLSPPS(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,strlen(a),b,c,d,strlen(d))
#define CALLOPPO(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,(d).c_str(),(d).size())
#define DEFSPSP(UN,LN,a,la,b,c,lc,d)               STDCALL(UN,LN)(a,la,b,c,lc,d)
#define CALLSPSP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(c),d)
#define CALLOPOP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),b,(c).c_str(),(c).size(),d)
#define DEFSPSS(UN,LN,a,la,b,c,lc,d,ld)               STDCALL(UN,LN)(a,la,b,c,lc,d,ld)
#define CALLSPSS(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(c),d,strlen(d))
#define CALLOPOO(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),b,(c).c_str(),(c).size(),(d).c_str(),(d).size())
#define DEFSSPP(UN,LN,a,la,b,lb,c,d)               STDCALL(UN,LN)(a,la,b,lb,c,d)
#define CALLSSPP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d)
#define CALLOOPP(UN,LN,a,b,c,d)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,d)
#define DEFSSPS(UN,LN,a,la,b,lb,c,d,ld)               STDCALL(UN,LN)(a,la,b,lb,c,d,ld)
#define CALLSSPS(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,strlen(d))
#define CALLOOPO(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,(d).c_str(),(d).size())
#define DEFSSSP(UN,LN,a,la,b,lb,c,lc,d)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d)
#define CALLSSSP(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d)
#define CALLOOOP(UN,LN,a,b,c,d)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),d)
#define DEFSSSS(UN,LN,a,la,b,lb,c,lc,d,ld)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld)
#define CALLSSSS(UN,LN,a,b,c,d)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d))
#define CALLOOOO(UN,LN,a,b,c,d)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size())
#define DEFPPPSP(UN,LN,a,b,c,d,ld,e)               STDCALL(UN,LN)(a,b,c,d,ld,e)
#define CALLPPPSP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)(a,b,c,d,strlen(d),e)
#define CALLPPPOP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)(a,b,c,(d).c_str(),(d).size(),e)
#define DEFPSSSS(UN,LN,a,b,lb,c,lc,d,ld,e,le)               STDCALL(UN,LN)(a,b,lb,c,lc,d,ld,e,le)
#define CALLPSSSS(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,b,strlen(b),c,strlen(c),d,strlen(d),e,strlen(e))
#define CALLPOOOO(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),(e).c_str(),(e).size())
#define DEFSPPPP(UN,LN,a,la,b,c,d,e)               STDCALL(UN,LN)(a,la,b,c,d,e)
#define CALLSPPPP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)(a,strlen(a),b,c,d,e)
#define CALLOPPPP(UN,LN,a,b,c,d,e)                 F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,d,e)
#define DEFSSPPP(UN,LN,a,la,b,lb,c,d,e)               STDCALL(UN,LN)(a,la,b,lb,c,d,e)
#define CALLSSPPP(UN,LN,a,b,c,d,e)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,e)
#define CALLOOPPP(UN,LN,a,b,c,d,e)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,d,e)
#define DEFSSPSS(UN,LN,a,la,b,lb,c,d,ld,e,le)               STDCALL(UN,LN)(a,la,b,lb,c,d,ld,e,le)
#define CALLSSPSS(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,strlen(d),e,strlen(e))
#define CALLOOPOO(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,(d).c_str(),(d).size(),(e).c_str(),(e).size())
#define DEFSSSPP(UN,LN,a,la,b,lb,c,lc,d,e)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,e)
#define CALLSSSPP(UN,LN,a,b,c,d,e)                       F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,e)
#define CALLOOOPP(UN,LN,a,b,c,d,e)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),d,e)
#define DEFSSSSP(UN,LN,a,la,b,lb,c,lc,d,ld,e)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e)
#define CALLSSSSP(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e)
#define CALLOOOOP(UN,LN,a,b,c,d,e)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),e)
#define DEFSSSSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,le)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,le)
#define CALLSSSSS(UN,LN,a,b,c,d,e)                             F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,strlen(e))
#define CALLOOOOO(UN,LN,a,b,c,d,e)                             F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),(e).c_str(),(e).size())
#define DEFSPPSSP(UN,LN,a,la,b,c,d,ld,e,le,f)               STDCALL(UN,LN)(a,la,b,c,d,ld,e,le,f)
#define CALLSPPSSP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)(a,strlen(a),b,c,d,strlen(d),e,strlen(e),f)
#define CALLOPPOOP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,(d).c_str(),(d).size(),(e).c_str(),(e).size(),f)
#define DEFSSPPPP(UN,LN,a,la,b,lb,c,d,e,f)               STDCALL(UN,LN)(a,la,b,lb,c,d,e,f)
#define CALLSSPPPP(UN,LN,a,b,c,d,e,f)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,e,f)
#define CALLOOPPPP(UN,LN,a,b,c,d,e,f)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,d,e,f)
#define DEFSSPPSP(UN,LN,a,la,b,lb,c,d,e,le,f)               STDCALL(UN,LN)(a,la,b,lb,c,d,e,le,f)
#define CALLSSPPSP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,e,strlen(e),f)
#define CALLOOPPOP(UN,LN,a,b,c,d,e,f)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,d,(e).c_str(),(e).size(),f)
#define DEFSSPPSS(UN,LN,a,la,b,lb,c,d,e,le,f,lf)               STDCALL(UN,LN)(a,la,b,lb,c,d,e,le,f,lf)
#define CALLSSPPSS(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,e,strlen(e),f,strlen(f))
#define CALLOOPPOO(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,d,(e).c_str(),(e).size(),(f).c_str(),(f).size())
#define DEFSSSPSP(UN,LN,a,la,b,lb,c,lc,d,e,le,f)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,e,le,f)
#define CALLSSSPSP(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,e,strlen(e),f)
#define CALLOOOPOP(UN,LN,a,b,c,d,e,f)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),d,(e).c_str(),(e).size(),f)
#define DEFSSSPSS(UN,LN,a,la,b,lb,c,lc,d,e,le,f,lf)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,e,le,f,lf)
#define CALLSSSPSS(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,e,strlen(e),f,strlen(f))
#define CALLOOOPOO(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),d,(e).c_str(),(e).size(),(f).c_str(),(f).size())
#define DEFSSSSPS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,f,lf)
#define CALLSSSSPS(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,f,strlen(f))
#define CALLOOOOPO(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),e,(f).c_str(),(f).size())
#define DEFSSSSSP(UN,LN,a,la,b,lb,c,lc,d,ld,e,le,f)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,le,f)
#define CALLSSSSSP(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,strlen(e),f)
#define CALLOOOOOP(UN,LN,a,b,c,d,e,f)                             F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),(e).c_str(),(e).size(),f)
#define DEFSSSSSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,le,f,lf)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,le,f,lf)
#define CALLSSSSSS(UN,LN,a,b,c,d,e,f)                                F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,strlen(e),f,strlen(f))
#define CALLOOOOOO(UN,LN,a,b,c,d,e,f)                                F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),(e).c_str(),(e).size(),(f).c_str(),(f).size())
#define DEFPSSSPSP(UN,LN,a,b,lb,c,lc,d,ld,e,f,lf,g)               STDCALL(UN,LN)(a,b,lb,c,lc,d,ld,e,f,lf,g)
#define CALLPSSSPSP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,b,strlen(b),c,strlen(c),d,strlen(d),e,f,strlen(f),g)
#define CALLPOOOPOP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),e,(f).c_str(),(f).size(),g)
#define DEFSPPPPPP(UN,LN,a,la,b,c,d,e,f,g)               STDCALL(UN,LN)(a,la,b,c,d,e,f,g)
#define CALLSPPPPPP(UN,LN,a,b,c,d,e,f,g)                 F_FUNC(UN,LN)(a,strlen(a),b,c,d,e,f,g)
#define CALLOPPPPPP(UN,LN,a,b,c,d,e,f,g)                 F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,d,e,f,g)
#define DEFSPPSSSP(UN,LN,a,la,b,c,d,ld,e,le,f,lf,g)               STDCALL(UN,LN)(a,la,b,c,d,ld,e,le,f,lf,g)
#define CALLSPPSSSP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,strlen(a),b,c,d,strlen(d),e,strlen(e),f,strlen(f),g)
#define CALLOPPOOOP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,(d).c_str(),(d).size(),(e).c_str(),(e).size(),(f).c_str(),(f).size(),g)
#define DEFSPSPPPS(UN,LN,a,la,b,c,lc,d,e,f,g,lg)               STDCALL(UN,LN)(a,la,b,c,lc,d,e,f,g,lg)
#define CALLSPSPPPS(UN,LN,a,b,c,d,e,f,g)                       F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(c),d,e,f,g,strlen(g))
#define CALLOPOPPPO(UN,LN,a,b,c,d,e,f,g)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),b,(c).c_str(),(c).size(),d,e,f,(g).c_str(),(g).size())
#define DEFSSPPPPP(UN,LN,a,la,b,lb,c,d,e,f,g)               STDCALL(UN,LN)(a,la,b,lb,c,d,e,f,g)
#define CALLSSPPPPP(UN,LN,a,b,c,d,e,f,g)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,e,f,g)
#define CALLOOPPPPP(UN,LN,a,b,c,d,e,f,g)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,d,e,f,g)
#define DEFSSPSSPP(UN,LN,a,la,b,lb,c,d,ld,e,le,f,g)               STDCALL(UN,LN)(a,la,b,lb,c,d,ld,e,le,f,g)
#define CALLSSPSSPP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,strlen(d),e,strlen(e),f,g)
#define CALLOOPOOPP(UN,LN,a,b,c,d,e,f,g)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,(d).c_str(),(d).size(),(e).c_str(),(e).size(),f,g)
#define DEFSSSPSSP(UN,LN,a,la,b,lb,c,lc,d,e,le,f,lf,g)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,e,le,f,lf,g)
#define CALLSSSPSSP(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,e,strlen(e),f,strlen(f),g)
#define CALLOOOPOOP(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),d,(e).c_str(),(e).size(),(f).c_str(),(f).size(),g)
#define DEFSSSSPPS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,g,lg)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,f,g,lg)
#define CALLSSSSPPS(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,f,g,strlen(g))
#define CALLOOOOPPO(UN,LN,a,b,c,d,e,f,g)                             F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),e,f,(g).c_str(),(g).size())
#define DEFSSSSPSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg)
#define CALLSSSSPSS(UN,LN,a,b,c,d,e,f,g)                                F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,f,strlen(f),g,strlen(g))
#define CALLOOOOPOO(UN,LN,a,b,c,d,e,f,g)                                F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),e,(f).c_str(),(f).size(),(g).c_str(),(g).size())
#define DEFPPPPSPPP(UN,LN,a,b,c,d,e,le,f,g,h)               STDCALL(UN,LN)(a,b,c,d,e,le,f,g,h)
#define CALLPPPPSPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,c,d,e,strlen(e),f,g,h)
#define CALLPPPPOPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,c,d,(e).c_str(),(e).size(),f,g,h)
#define DEFPPPPSPSP(UN,LN,a,b,c,d,e,le,f,g,lg,h)               STDCALL(UN,LN)(a,b,c,d,e,le,f,g,lg,h)
#define CALLPPPPSPSP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,b,c,d,e,strlen(e),f,g,strlen(g),h)
#define CALLPPPPOPOP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,b,c,d,(e).c_str(),(e).size(),f,(g).c_str(),(g).size(),h)
#define DEFPPPPSPSS(UN,LN,a,b,c,d,e,le,f,g,lg,h,lh)               STDCALL(UN,LN)(a,b,c,d,e,le,f,g,lg,h,lh)
#define CALLPPPPSPSS(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)(a,b,c,d,e,strlen(e),f,g,strlen(g),h,strlen(h))
#define CALLPPPPOPOO(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)(a,b,c,d,(e).c_str(),(e).size(),f,(g).c_str(),(g).size(),(h).c_str(),(h).size())
#define DEFPPSPPPPP(UN,LN,a,b,c,lc,d,e,f,g,h)               STDCALL(UN,LN)(a,b,c,lc,d,e,f,g,h)
#define CALLPPSPPPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,c,strlen(c),d,e,f,g,h)
#define CALLPPOPPPPP(UN,LN,a,b,c,d,e,f,g,h)                 F_FUNC(UN,LN)(a,b,(c).c_str(),(c).size(),d,e,f,g,h)
#define DEFPSPSPPPP(UN,LN,a,b,lb,c,d,ld,e,f,g,h)               STDCALL(UN,LN)(a,b,lb,c,d,ld,e,f,g,h)
#define CALLPSPSPPPP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,b,strlen(b),c,d,strlen(d),e,f,g,h)
#define CALLPOPOPPPP(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,(b).c_str(),(b).size(),c,(d).c_str(),(d).size(),e,f,g,h)
#define DEFSPPPPPPS(UN,LN,a,la,b,c,d,e,f,g,h,lh)               STDCALL(UN,LN)(a,la,b,c,d,e,f,g,h,lh)
#define CALLSPPPPPPS(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)(a,strlen(a),b,c,d,e,f,g,h,strlen(h))
#define CALLOPPPPPPO(UN,LN,a,b,c,d,e,f,g,h)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,d,e,f,g,(h).c_str(),(h).size())
#define DEFSSSPPPPP(UN,LN,a,la,b,lb,c,lc,d,e,f,g,h)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,e,f,g,h)
#define CALLSSSPPPPP(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,e,f,g,h)
#define CALLOOOPPPPP(UN,LN,a,b,c,d,e,f,g,h)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),d,e,f,g,h)
#define DEFPSSSSSSPS(UN,LN,a,b,lb,c,lc,d,ld,e,le,f,lf,g,lg,h,i,li)               STDCALL(UN,LN)(a,b,lb,c,lc,d,ld,e,le,f,lf,g,lg,h,i,li)
#define CALLPSSSSSSPS(UN,LN,a,b,c,d,e,f,g,h,i)                                   F_FUNC(UN,LN)(a,b,strlen(b),c,strlen(c),d,strlen(d),e,strlen(e),f,strlen(f),g,strlen(g),h,i,strlen(i))
#define CALLPOOOOOOPO(UN,LN,a,b,c,d,e,f,g,h,i)                                   F_FUNC(UN,LN)(a,(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),(e).c_str(),(e).size(),(f).c_str(),(f).size(),(g).c_str(),(g).size(),h,(i).c_str(),(i).size())
#define DEFSPPSPPPSP(UN,LN,a,la,b,c,d,ld,e,f,g,h,lh,i)               STDCALL(UN,LN)(a,la,b,c,d,ld,e,f,g,h,lh,i)
#define CALLSPPSPPPSP(UN,LN,a,b,c,d,e,f,g,h,i)                       F_FUNC(UN,LN)(a,strlen(a),b,c,d,strlen(d),e,f,g,h,strlen(h),i)
#define CALLOPPOPPPOP(UN,LN,a,b,c,d,e,f,g,h,i)                       F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,(d).c_str(),(d).size(),e,f,g,(h).c_str(),(h).size(),i)
#define DEFSPPSSPSPS(UN,LN,a,la,b,c,d,ld,e,le,f,g,lg,h,i,li)               STDCALL(UN,LN)(a,la,b,c,d,ld,e,le,f,g,lg,h,i,li)
#define CALLSPPSSPSPS(UN,LN,a,b,c,d,e,f,g,h,i)                             F_FUNC(UN,LN)(a,strlen(a),b,c,d,strlen(d),e,strlen(e),f,g,strlen(g),h,i,strlen(i))
#define CALLOPPOOPOPO(UN,LN,a,b,c,d,e,f,g,h,i)                             F_FUNC(UN,LN)((a).c_str(),(a).size(),b,c,(d).c_str(),(d).size(),(e).c_str(),(e).size(),f,(g).c_str(),(g).size(),h,(i).c_str(),(i).size())
#define DEFSSSSPSSSS(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg,h,lh,i,li)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg,h,lh,i,li)
#define CALLSSSSPSSSS(UN,LN,a,b,c,d,e,f,g,h,i)                                      F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,f,strlen(f),g,strlen(g),h,strlen(h),i,strlen(i))
#define CALLOOOOPOOOO(UN,LN,a,b,c,d,e,f,g,h,i)                                      F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),e,(f).c_str(),(f).size(),(g).c_str(),(g).size(),(h).c_str(),(h).size(),(i).c_str(),(i).size())
#define DEFPPPPPSPPPP(UN,LN,a,b,c,d,e,f,lf,g,h,i,j)               STDCALL(UN,LN)(a,b,c,d,e,f,lf,g,h,i,j)
#define CALLPPPPPSPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                 F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(f),g,h,i,j)
#define CALLPPPPPOPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                 F_FUNC(UN,LN)(a,b,c,d,e,(f).c_str(),(f).size(),g,h,i,j)
#define DEFPPPPPSPPSP(UN,LN,a,b,c,d,e,f,lf,g,h,i,li,j)               STDCALL(UN,LN)(a,b,c,d,e,f,lf,g,h,i,li,j)
#define CALLPPPPPSPPSP(UN,LN,a,b,c,d,e,f,g,h,i,j)                    F_FUNC(UN,LN)(a,b,c,d,e,f,strlen(f),g,h,i,strlen(i),j)
#define CALLPPPPPOPPOP(UN,LN,a,b,c,d,e,f,g,h,i,j)                    F_FUNC(UN,LN)(a,b,c,d,e,(f).c_str(),(f).size(),g,h,(i).c_str(),(i).size(),j)
#define DEFSPSPSPPPPS(UN,LN,a,la,b,c,lc,d,e,le,f,g,h,i,j,lj)               STDCALL(UN,LN)(a,la,b,c,lc,d,e,le,f,g,h,i,j,lj)
#define CALLSPSPSPPPPS(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(c),d,e,strlen(e),f,g,h,i,j,strlen(j))
#define CALLOPOPOPPPPO(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),b,(c).c_str(),(c).size(),d,(e).c_str(),(e).size(),f,g,h,i,(j).c_str(),(j).size())
#define DEFSPSSSPSSPS(UN,LN,a,la,b,c,lc,d,ld,e,le,f,g,lg,h,lh,i,j,lj)               STDCALL(UN,LN)(a,la,b,c,lc,d,ld,e,le,f,g,lg,h,lh,i,j,lj)
#define CALLSPSSSPSSPS(UN,LN,a,b,c,d,e,f,g,h,i,j)                                   F_FUNC(UN,LN)(a,strlen(a),b,c,strlen(c),d,strlen(d),e,strlen(e),f,g,strlen(g),h,strlen(h),i,j,strlen(j))
#define CALLOPOOOPOOPO(UN,LN,a,b,c,d,e,f,g,h,i,j)                                   F_FUNC(UN,LN)((a).c_str(),(a).size(),b,(c).c_str(),(c).size(),(d).c_str(),(d).size(),(e).c_str(),(e).size(),f,(g).c_str(),(g).size(),(h).c_str(),(h).size(),i,(j).c_str(),(j).size())
#define DEFSSPSPPPPPS(UN,LN,a,la,b,lb,c,d,ld,e,f,g,h,i,j,lj)               STDCALL(UN,LN)(a,la,b,lb,c,d,ld,e,f,g,h,i,j,lj)
#define CALLSSPSPPPPPS(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,strlen(d),e,f,g,h,i,j,strlen(j))
#define CALLOOPOPPPPPO(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,(d).c_str(),(d).size(),e,f,g,h,i,(j).c_str(),(j).size())
#define DEFSSPSPPSPPP(UN,LN,a,la,b,lb,c,d,ld,e,f,g,lg,h,i,j)               STDCALL(UN,LN)(a,la,b,lb,c,d,ld,e,f,g,lg,h,i,j)
#define CALLSSPSPPSPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,strlen(d),e,f,g,strlen(g),h,i,j)
#define CALLOOPOPPOPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)                          F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,(d).c_str(),(d).size(),e,f,(g).c_str(),(g).size(),h,i,j)
#define DEFSSSSSSSPPPP(UN,LN,a,la,b,lb,c,lc,d,ld,e,le,f,lf,g,lg,h,i,j,k)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,le,f,lf,g,lg,h,i,j,k)
#define CALLSSSSSSSPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k)                                   F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,strlen(e),f,strlen(f),g,strlen(g),h,i,j,k)
#define CALLOOOOOOOPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k)                                   F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),(e).c_str(),(e).size(),(f).c_str(),(f).size(),(g).c_str(),(g).size(),h,i,j,k)
#define DEFSSSSPSSSSPPP(UN,LN,a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg,h,lh,i,li,j,k,l)               STDCALL(UN,LN)(a,la,b,lb,c,lc,d,ld,e,f,lf,g,lg,h,lh,i,li,j,k,l)
#define CALLSSSSPSSSSPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l)                                      F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,strlen(c),d,strlen(d),e,f,strlen(f),g,strlen(g),h,strlen(h),i,strlen(i),j,k,l)
#define CALLOOOOPOOOOPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l)                                      F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),(c).c_str(),(c).size(),(d).c_str(),(d).size(),e,(f).c_str(),(f).size(),(g).c_str(),(g).size(),(h).c_str(),(h).size(),(i).c_str(),(i).size(),j,k,l)
#define DEFSSPPPPPPPPPPPP(UN,LN,a,la,b,lb,c,d,e,f,g,h,i,j,k,l,m,n)               STDCALL(UN,LN)(a,la,b,lb,c,d,e,f,g,h,i,j,k,l,m,n)
#define CALLSSPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n)                    F_FUNC(UN,LN)(a,strlen(a),b,strlen(b),c,d,e,f,g,h,i,j,k,l,m,n)
#define CALLOOPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n)                    F_FUNC(UN,LN)((a).c_str(),(a).size(),(b).c_str(),(b).size(),c,d,e,f,g,h,i,j,k,l,m,n)
#define DEFPPPPPPPPPPPPPPPPPPPSPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,lt,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,lt,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)
#define CALLPPPPPPPPPPPPPPPPPPPSPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,strlen(t),u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)
#define CALLPPPPPPPPPPPPPPPPPPPOPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)                 F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,(t).c_str(),(t).size(),u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L)

#endif

/* Appels et signatures sans chaine de caractères */
#define DEF0(UN,LN)               STDCALL(UN,LN)( void )
#define CALL0(UN,LN)              F_FUNC(UN,LN)()
#define DEFP(UN,LN,a)               STDCALL(UN,LN)(a)
#define CALLP(UN,LN,a)              F_FUNC(UN,LN)(a)
#define CALLP(UN,LN,a)              F_FUNC(UN,LN)(a)
#define DEFPP(UN,LN,a,b)               STDCALL(UN,LN)(a,b)
#define CALLPP(UN,LN,a,b)              F_FUNC(UN,LN)(a,b)
#define CALLPP(UN,LN,a,b)              F_FUNC(UN,LN)(a,b)
#define DEFPPP(UN,LN,a,b,c)               STDCALL(UN,LN)(a,b,c)
#define CALLPPP(UN,LN,a,b,c)              F_FUNC(UN,LN)(a,b,c)
#define CALLPPP(UN,LN,a,b,c)              F_FUNC(UN,LN)(a,b,c)
#define DEFPPPP(UN,LN,a,b,c,d)               STDCALL(UN,LN)(a,b,c,d)
#define CALLPPPP(UN,LN,a,b,c,d)              F_FUNC(UN,LN)(a,b,c,d)
#define CALLPPPP(UN,LN,a,b,c,d)              F_FUNC(UN,LN)(a,b,c,d)
#define DEFPPPPP(UN,LN,a,b,c,d,e)               STDCALL(UN,LN)(a,b,c,d,e)
#define CALLPPPPP(UN,LN,a,b,c,d,e)              F_FUNC(UN,LN)(a,b,c,d,e)
#define CALLPPPPP(UN,LN,a,b,c,d,e)              F_FUNC(UN,LN)(a,b,c,d,e)
#define DEFPPPPPP(UN,LN,a,b,c,d,e,f)               STDCALL(UN,LN)(a,b,c,d,e,f)
#define CALLPPPPPP(UN,LN,a,b,c,d,e,f)              F_FUNC(UN,LN)(a,b,c,d,e,f)
#define CALLPPPPPP(UN,LN,a,b,c,d,e,f)              F_FUNC(UN,LN)(a,b,c,d,e,f)
#define DEFPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h)
#define CALLPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h)
#define CALLPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h)
#define DEFPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j)
#define CALLPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j)
#define CALLPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j)
#define DEFPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m)
#define CALLPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m)
#define CALLPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m)
#define DEFPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)               STDCALL(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)
#define CALLPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)
#define CALLPPPPPPPPPPPPPPPPPP(UN,LN,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)              F_FUNC(UN,LN)(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r)

#endif
